apiVersion: v1
kind: ServiceAccount
metadata:
  name: firemud-hosted-identity-controller
  namespace: firemud-system
  labels:
    app.kubernetes.io/name: hosted-environment-identity-controller
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: firemud
    firemud.dev/managed-by: hosted-identity-controller
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: firemud-hosted-identity-requester
  namespace: firemud-system
  labels:
    app.kubernetes.io/name: hosted-environment-identity-controller
    app.kubernetes.io/component: lifecycle-requester
    app.kubernetes.io/part-of: firemud
    firemud.dev/managed-by: hosted-identity-controller
automountServiceAccountToken: true
