apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: firemud
  name: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager:v0.27.0
          args: ["--config.file=/etc/alertmanager/alertmanager.yml"]
          ports:
            - containerPort: 9093
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager
      volumes:
        - name: config
          configMap:
            name: alertmanager-config
---
apiVersion: v1
kind: Service
metadata:
  namespace: firemud
  name: alertmanager
spec:
  selector:
    app: alertmanager
  ports:
    - port: 9093
      targetPort: 9093
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: firemud
  name: alertmanager-config
data:
  alertmanager.yml: |
    route:
      receiver: 'default'
    receivers:
      - name: 'default'
        webhook_configs:
          - url: 'http://logging-admin-service:8080/api/v1/alerts'
            send_resolved: true
