#!/usr/bin/env python3

import argparse
import json
from pathlib import Path
import sys


REPO_ROOT = Path(__file__).resolve().parents[2]
PUBLICATION_SPEC_PATH = REPO_ROOT / "config/settings/platform-settings-publication.json"
METADATA_PATHS = [
    REPO_ROOT / "services/game-session-service/src/main/resources/META-INF/additional-spring-configuration-metadata.json",
    REPO_ROOT / "services/game-logic-service/src/main/resources/META-INF/additional-spring-configuration-metadata.json",
]
SCHEMA_OUTPUT_PATH = REPO_ROOT / "design/architecture/generated/platform-settings-schema.json"
REFERENCE_OUTPUT_PATH = REPO_ROOT / "design/architecture/generated/platform-settings-reference.md"


def load_json(path: Path) -> dict:
    return json.loads(path.read_text())


def render_value(value) -> str:
    if value is None:
        return "`(none)`"
    if isinstance(value, bool):
        return f"`{str(value).lower()}`"
    return f"`{value}`"


def build_outputs() -> tuple[dict, str]:
    publication_spec = load_json(PUBLICATION_SPEC_PATH)
    property_specs = publication_spec["properties"]

    metadata_by_name = {}
    hints_by_name = {}
    for metadata_path in METADATA_PATHS:
        metadata = load_json(metadata_path)
        for property_node in metadata.get("properties", []):
            metadata_by_name[property_node["name"]] = property_node
        for hint_node in metadata.get("hints", []):
            if "values" in hint_node:
                hints_by_name[hint_node["name"]] = hint_node["values"]

    schema = {
        "schemaVersion": publication_spec["schemaVersion"],
        "description": publication_spec["description"],
        "generatorTask": "updatePlatformSettingsDocs",
        "checkedInSchemaPath": str(SCHEMA_OUTPUT_PATH.relative_to(REPO_ROOT)),
        "checkedInReferencePath": str(REFERENCE_OUTPUT_PATH.relative_to(REPO_ROOT)),
        "sources": {
            "springMetadataFiles": [str(path.relative_to(REPO_ROOT)) for path in METADATA_PATHS],
            "publicationSpec": str(PUBLICATION_SPEC_PATH.relative_to(REPO_ROOT)),
        },
        "domains": [],
    }

    markdown_lines = [
        "# FireMUD Platform Settings Reference",
        "",
        "This reference is generated from the surfaced Spring settings metadata plus `config/settings/platform-settings-publication.json`. **Do not edit this file manually.** After changing a surfaced pre-`06` settings definition, run `./gradlew updatePlatformSettingsDocs`.",
        "",
        "The machine-readable companion schema is [`platform-settings-schema.json`](./platform-settings-schema.json). Later operator/admin and creator tooling should consume that JSON output rather than re-describing keys in a separate schema.",
    ]

    seen_property_names = set()
    for domain_spec in publication_spec["domains"]:
        domain_output = {
            "name": domain_spec["name"],
            "keyPrefix": domain_spec["keyPrefix"],
            "service": domain_spec["service"],
            "owner": domain_spec["owner"],
            "description": domain_spec["description"],
            "referenceDoc": domain_spec.get("referenceDoc"),
            "runtimeSurface": domain_spec.get("runtimeSurface"),
            "properties": [],
        }
        schema["domains"].append(domain_output)

        markdown_lines.extend(
            [
                "",
                f"## `{domain_spec['keyPrefix']}`",
                "",
                domain_spec["description"],
                "",
                f"- Service owner: `{domain_spec['service']}`",
                f"- Current operator-default owner: `{domain_spec['owner']}`",
            ]
        )
        if domain_spec.get("referenceDoc"):
            relative_doc = Path("..") / Path(domain_spec["referenceDoc"]).relative_to("design/architecture")
            markdown_lines.append(
                f"- Service configuration notes: [`{domain_spec['referenceDoc']}`]({relative_doc.as_posix()})"
            )
        if domain_spec.get("runtimeSurface"):
            markdown_lines.append(f"- Runtime/effective inspection surface: `{domain_spec['runtimeSurface']}`")
        markdown_lines.extend(
            [
                "",
                "| Key | Group | Description | Default | Valid values or range | Current scope | Future scope | Hot reloadable | Advanced | Example |",
                "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
            ]
        )

        for property_name in domain_spec["properties"]:
            seen_property_names.add(property_name)
            metadata_node = metadata_by_name.get(property_name)
            if metadata_node is None:
                raise SystemExit(f"Missing Spring metadata for surfaced property '{property_name}'")
            property_spec = property_specs.get(property_name)
            if property_spec is None:
                raise SystemExit(f"Missing publication spec for surfaced property '{property_name}'")

            allowed_values = []
            if property_name in hints_by_name:
                for value_node in hints_by_name[property_name]:
                    allowed_value = {"value": value_node["value"]}
                    if "description" in value_node:
                        allowed_value["description"] = value_node["description"]
                    allowed_values.append(allowed_value)
            elif metadata_node["type"] == "java.lang.Boolean":
                allowed_values = [{"value": "true"}, {"value": "false"}]

            property_output = {
                "name": property_name,
                "type": metadata_node["type"],
                "sourceType": metadata_node["sourceType"],
                "description": metadata_node["description"],
                "defaultValue": metadata_node.get("defaultValue"),
                "domain": domain_spec["name"],
                "group": property_spec["group"],
                "scope": property_spec["scope"],
                "futureScope": property_spec["futureScope"],
                "hotReloadable": property_spec["hotReloadable"],
                "advanced": property_spec["advanced"],
                "exampleValue": property_spec.get("exampleValue"),
                "allowedValues": allowed_values,
            }
            if "constraints" in property_spec:
                property_output["constraints"] = property_spec["constraints"]
            domain_output["properties"].append(property_output)

            if "constraints" in property_spec:
                valid_values_or_range = property_spec["constraints"]
            elif allowed_values:
                valid_values_or_range = ", ".join(f"`{value['value']}`" for value in allowed_values)
            else:
                valid_values_or_range = metadata_node["type"]

            markdown_lines.append(
                f"| `{property_name}` | `{property_spec['group']}` | {metadata_node['description']} | {render_value(metadata_node.get('defaultValue'))} | {valid_values_or_range} | `{property_spec['scope']}` | `{property_spec['futureScope']}` | `{'yes' if property_spec['hotReloadable'] else 'no'}` | `{'yes' if property_spec['advanced'] else 'no'}` | {render_value(property_spec.get('exampleValue'))} |"
            )

    extra_property_specs = sorted(set(property_specs.keys()) - seen_property_names)
    if extra_property_specs:
        raise SystemExit(
            "Publication spec contains unsupported surfaced properties: "
            + ", ".join(extra_property_specs)
        )

    return schema, "\n".join(markdown_lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", choices=["write", "check"], required=True)
    args = parser.parse_args()

    schema, reference = build_outputs()
    schema_text = json.dumps(schema, indent=2) + "\n"

    if args.mode == "write":
        SCHEMA_OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
        REFERENCE_OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
        SCHEMA_OUTPUT_PATH.write_text(schema_text)
        REFERENCE_OUTPUT_PATH.write_text(reference)
        return 0

    if not SCHEMA_OUTPUT_PATH.exists():
        raise SystemExit(
            f"Missing checked-in schema at {SCHEMA_OUTPUT_PATH.relative_to(REPO_ROOT)}. Run ./gradlew updatePlatformSettingsDocs"
        )
    if not REFERENCE_OUTPUT_PATH.exists():
        raise SystemExit(
            f"Missing checked-in reference at {REFERENCE_OUTPUT_PATH.relative_to(REPO_ROOT)}. Run ./gradlew updatePlatformSettingsDocs"
        )
    if SCHEMA_OUTPUT_PATH.read_text() != schema_text:
        raise SystemExit("Generated platform settings schema is out of date. Run ./gradlew updatePlatformSettingsDocs")
    if REFERENCE_OUTPUT_PATH.read_text() != reference:
        raise SystemExit("Generated platform settings reference is out of date. Run ./gradlew updatePlatformSettingsDocs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
