#!/usr/bin/env bash
# Generate gRPC API documentation for all proto files
set -euo pipefail

OUT_DIR="design/grpc-docs"
mkdir -p "$OUT_DIR"

readarray -t PROTO_FILES < <(find protos -name '*.proto' | sort)

TEMP_PROTO_DOC="$(mktemp "$OUT_DIR/.grpc-api-proto.XXXXXX")"
TEMP_OUTPUT="$(mktemp "$OUT_DIR/.grpc-api-output.XXXXXX")"
TEMP_NORMALIZED="$(mktemp "$OUT_DIR/.grpc-api-normalized.XXXXXX")"
cleanup() {
  rm -f "$TEMP_PROTO_DOC" "$TEMP_OUTPUT" "$TEMP_NORMALIZED"
}
trap cleanup EXIT

protoc -I protos \
  --experimental_allow_proto3_optional \
  --doc_out="$OUT_DIR" \
  --doc_opt=markdown,"$(basename "$TEMP_PROTO_DOC")" \
  "${PROTO_FILES[@]}"

# Prepend usage instructions
cat > "$TEMP_OUTPUT" <<'EOF'
# Protocol Documentation

This reference is generated from the protobuf files under `protos/` using
[protoc-gen-doc](https://github.com/pseudomuto/protoc-gen-doc). **Do not edit this file manually.**
After editing any `.proto` definitions, run the following commands:

```bash
BUF_WORKSPACE_CONFIG=config/protobuf/buf.work.yaml buf lint
./gradlew generateProto
./dev-tools/docs/generate-grpc-docs.sh
```

to regenerate these docs and verify schema/doc consistency.

Refer to the [gRPC API Style Guide](../architecture/system-architecture-grpc.md)
for conventions on schema evolution and error handling. See each service's
`README.md` under `services/` for high-level explanations of its endpoints.

EOF

tail -n +2 "$TEMP_PROTO_DOC" >> "$TEMP_OUTPUT"

# Keep generated output stable and diff-hygienic across protoc-gen-doc versions.
awk '
  {
    sub(/[[:space:]]+$/, "")
    if ($0 == "") {
      pending_blank_lines++
      next
    }
    while (pending_blank_lines > 0) {
      print ""
      pending_blank_lines--
    }
    print
  }
' "$TEMP_OUTPUT" > "$TEMP_NORMALIZED"
mv "$TEMP_NORMALIZED" "$TEMP_OUTPUT"
mv "$TEMP_OUTPUT" "$OUT_DIR/grpc-api.md"

echo "Generated gRPC docs in $OUT_DIR"
