#!/usr/bin/env bash
# Generate gRPC API documentation for all proto files
set -euo pipefail

OUT_DIR="design/grpc-docs"
mkdir -p "$OUT_DIR"

readarray -t PROTO_FILES < <(find protos -name '*.proto' | sort)

TEMP_FILE="$(mktemp)"

protoc -I protos \
  --experimental_allow_proto3_optional \
  --doc_out="$OUT_DIR" \
  --doc_opt=markdown,"$(basename "$TEMP_FILE")" \
  "${PROTO_FILES[@]}"

# Prepend usage instructions
cat > "$OUT_DIR/grpc-api.md" <<'EOF'
# Protocol Documentation

This reference is generated from the protobuf files under `protos/` using
[protoc-gen-doc](https://github.com/pseudomuto/protoc-gen-doc). **Do not edit this file manually.**
After editing any `.proto` definitions, run the following commands:

```bash
BUF_WORKSPACE_CONFIG=config/protobuf/buf.work.yaml buf lint
./gradlew generateProto
./dev-tools/docs/generate-grpc-docs.sh
```

to regenerate these docs and verify schema/doc consistency.

Refer to the [gRPC API Style Guide](../architecture/system-architecture-grpc.md)
for conventions on schema evolution and error handling. See each service's
`README.md` under `services/` for high-level explanations of its endpoints.

EOF

tail -n +2 "$OUT_DIR/$(basename "$TEMP_FILE")" >> "$OUT_DIR/grpc-api.md"
rm "$OUT_DIR/$(basename "$TEMP_FILE")"

echo "Generated gRPC docs in $OUT_DIR"
