{{- if .Values.redisCoord.resetAofOnHelmUpgrade }}
apiVersion: batch/v1
kind: Job
metadata:
  name: redis-coord-wipe-aof
  namespace: {{ .Release.Namespace }}
  labels:
    app: redis-coord
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: wipe
          image: busybox
          command:
            - sh
            - -c
            - rm -rf /mnt/redis/*
          volumeMounts:
            - name: redis-coord-data
              mountPath: /mnt/redis
      volumes:
        - name: redis-coord-data
          persistentVolumeClaim:
            claimName: redis-coord-data
{{- end }}
