package net.firedevops.firemud.gamesession.service;

public interface RemoteFollowupRuntimeService {
  ScheduleOutcome scheduleFollowup(ScheduleRequest request);

  ResultOutcome recordResult(ResultRequest request);

  void abandonFollowup(long tenantId, String followupId, String failureCode, String failureMessage);

  int reconcileResults(long tenantId, String originRegionId, long currentOriginRegionEpoch);

  int reconcileTimeouts(
      long tenantId, String originRegionId, long currentOriginRegionEpoch, long currentTickId);

  record ScheduleRequest(
      long tenantId,
      String commandId,
      String coordinatorId,
      long originGameInstanceId,
      String originRegionId,
      long originRegionEpoch,
      long targetGameInstanceId,
      String targetRegionId,
      long targetRegionEpoch,
      long targetDueTickId,
      long originDeadlineRegionEpoch,
      long originDeadlineTickId,
      String lateResultPolicy,
      String followupId,
      String effectKey,
      String targetEntityId,
      String payloadJson,
      String payloadKind,
      String requestedCommand,
      boolean requiresSoloTick,
      String playableStateScope,
      String worldSlug,
      String realmSlug,
      Long pointerVersion,
      String scriptPatchVersion,
      String pluginId,
      String pluginVersionId,
      String automationDispatchId,
      String automationWorkItemId,
      String scriptId,
      String originSourceKind,
      String originSourceState,
      Long originSourceOrdinal,
      Long originSourceDueTickId,
      Long originSourceDueAtMs,
      String eventType,
      String eventSchemaVersion,
      String scriptEventId,
      String triggerMode,
      String readSnapshotToken,
      String eventPayloadJson) {
    public ScheduleRequest(
        long tenantId,
        String commandId,
        String coordinatorId,
        long originGameInstanceId,
        String originRegionId,
        long originRegionEpoch,
        long targetGameInstanceId,
        String targetRegionId,
        long targetRegionEpoch,
        long targetDueTickId,
        long originDeadlineRegionEpoch,
        long originDeadlineTickId,
        String lateResultPolicy,
        String followupId,
        String effectKey,
        String targetEntityId,
        String payloadJson,
        String payloadKind,
        String requestedCommand,
        boolean requiresSoloTick,
        String playableStateScope,
        String worldSlug,
        String realmSlug,
        Long pointerVersion,
        String scriptPatchVersion,
        String pluginId,
        String pluginVersionId,
        String automationDispatchId,
        String automationWorkItemId,
        String scriptId,
        String originSourceKind,
        String originSourceState,
        Long originSourceOrdinal,
        Long originSourceDueTickId,
        Long originSourceDueAtMs) {
      this(
          tenantId,
          commandId,
          coordinatorId,
          originGameInstanceId,
          originRegionId,
          originRegionEpoch,
          targetGameInstanceId,
          targetRegionId,
          targetRegionEpoch,
          targetDueTickId,
          originDeadlineRegionEpoch,
          originDeadlineTickId,
          lateResultPolicy,
          followupId,
          effectKey,
          targetEntityId,
          payloadJson,
          payloadKind,
          requestedCommand,
          requiresSoloTick,
          playableStateScope,
          worldSlug,
          realmSlug,
          pointerVersion,
          scriptPatchVersion,
          pluginId,
          pluginVersionId,
          automationDispatchId,
          automationWorkItemId,
          scriptId,
          originSourceKind,
          originSourceState,
          originSourceOrdinal,
          originSourceDueTickId,
          originSourceDueAtMs,
          null,
          null,
          null,
          null,
          null,
          null);
    }
  }

  record ResultRequest(
      long tenantId,
      String resultId,
      String coordinatorId,
      String followupId,
      long originGameInstanceId,
      String originRegionId,
      long originRegionEpoch,
      long targetGameInstanceId,
      String targetRegionId,
      long targetRegionEpoch,
      String outcome,
      String resultPayloadJson,
      String resultCommandId,
      String resultErrorCode,
      String resultMessage) {}

  record ScheduleOutcome(
      String coordinatorId,
      String followupId,
      boolean coordinatorCreated,
      boolean followupCreated) {}

  record ResultOutcome(
      String coordinatorState,
      String followupStatus,
      boolean lateResult,
      boolean reconciledLateResult) {}
}
