apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: internal-services
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: NotIn
        values:
          - spring-cloud-gateway
          - tcp-proxy-service
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 8080
