{{- $gatewayWsTls := .Values.previewStack.gatewayWsTls | default (dict) }}
{{- $clusterIssuer := $gatewayWsTls.clusterIssuer | default "firemud-ca-issuer" }}
{{- $certificateIdentityMode := include "firemud.certificateIdentityMode" . | trim }}
{{- if and .Values.previewStack.enabled $gatewayWsTls.enabled (eq $certificateIdentityMode "standalone") }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "firemud.gatewayWsServerSecretName" . | trim }}
  labels:
{{ include "firemud.commonLabels" . | indent 4 }}
spec:
  secretName: {{ include "firemud.gatewayWsServerSecretName" . | trim }}
  privateKey:
    algorithm: RSA
    size: 2048
    encoding: PKCS8
    rotationPolicy: Always
  isCA: false
  revisionHistoryLimit: 1
  dnsNames:
    - {{ printf "spring-cloud-gateway-mtls.%s.svc.cluster.local" .Release.Namespace | quote }}
  usages:
    - digital signature
    - key encipherment
    - server auth
  encodeUsagesInRequest: true
  issuerRef:
    name: {{ $clusterIssuer | quote }}
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "firemud.gatewayWsClientSecretName" . | trim }}
  labels:
{{ include "firemud.commonLabels" . | indent 4 }}
spec:
  secretName: {{ include "firemud.gatewayWsClientSecretName" . | trim }}
  privateKey:
    algorithm: RSA
    size: 2048
    encoding: PKCS8
    rotationPolicy: Always
  isCA: false
  revisionHistoryLimit: 1
  uris:
    - {{ printf "spiffe://firemud/ns/%s/sa/tcp-proxy-service" .Release.Namespace | quote }}
  usages:
    - digital signature
    - key encipherment
    - client auth
  encodeUsagesInRequest: true
  issuerRef:
    name: {{ $clusterIssuer | quote }}
    kind: ClusterIssuer
    group: cert-manager.io
{{- end }}
