{{- $telnetTls := .Values.previewStack.telnetTls | default (dict) }}
{{- $telnetTlsSecretName := $telnetTls.secretName | default "" }}
{{- if $telnetTls.enabled }}
{{- $telnetTlsSecretName = required "previewStack.telnetTls.secretName is required when Telnet TLS is enabled" $telnetTls.secretName }}
{{- end }}
{{- if and .Values.previewStack.enabled $telnetTls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $telnetTlsSecretName }}
  labels:
{{ include "firemud.commonLabels" . | indent 4 }}
spec:
  secretName: {{ $telnetTlsSecretName }}
  privateKey:
    algorithm: RSA
    encoding: PKCS8
  dnsNames:
    - {{ .Values.preview.hostname | quote }}
  issuerRef:
    name: {{ $telnetTls.clusterIssuer | quote }}
    kind: ClusterIssuer
{{- end }}
