repos:
  - repo: local
    hooks:
      - id: spotless
        name: Spotless
        entry: ./gradlew spotlessCheck
        language: system
        pass_filenames: false
      - id: markdownlint
        name: markdownlint
        entry: ./gradlew lintMarkdown
        language: system
        pass_filenames: false
      - id: checkstyle
        name: Checkstyle
        entry: ./gradlew checkstyleMain
        language: system
        pass_filenames: false
      - id: spotbugs
        name: SpotBugs
        entry: ./gradlew spotbugsMain
        language: system
        pass_filenames: false
      - id: buf
        name: Buf Lint
        entry: buf lint
        language: system
        pass_filenames: false
      - id: hadolint
        name: Dockerfile Lint
        entry: hadolint -c config/hadolint/hadolint.yaml
        language: system
        files: (?i)^Dockerfile$|\.Dockerfile$
      - id: frontend-lint
        name: Frontend ESLint
        entry: bash -c 'cd web-client && npm run lint && npm run format:fix'
        language: system
        pass_filenames: false
      - id: link-check
        name: Link Check
        entry: ./dev-tools/link-check.sh
        language: script
        pass_filenames: false
      - id: shellcheck
        name: ShellCheck
        entry: bash -c 'find dev-tools -name "*.sh" -print0 | xargs -0 shellcheck'
        language: system
        pass_filenames: false
