repos:
  - repo: local
    hooks:
      - id: spotless
        name: Spotless
        entry: ./gradlew spotlessCheck
        language: system
        pass_filenames: false
      - id: markdownlint
        name: markdownlint
        entry: ./gradlew lintMarkdown
        language: system
        pass_filenames: false
      - id: checkstyle
        name: Checkstyle
        entry: ./gradlew checkstyleMain
        language: system
        pass_filenames: false
      - id: spotbugs
        name: SpotBugs
        entry: ./gradlew spotbugsMain
        language: system
        pass_filenames: false
      - id: buf
        name: Buf Lint
        entry: buf lint
        language: system
        pass_filenames: false
