site_name: FireMUD Documentation
site_url: https://benhook1013.github.io/FireMUD/
repo_url: https://github.com/benhook1013/FireMUD
repo_name: benhook1013/FireMUD
docs_dir: build/pages-docs
site_dir: build/public-site
use_directory_urls: true

theme:
  name: material
  features:
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search

markdown_extensions:
  - tables
  - toc:
      permalink: true
