package net.firedevops.firemud.gamedesign.repository;

import static org.assertj.core.api.Assertions.assertThat;

import java.sql.DriverManager;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.List;
import net.firedevops.firemud.gamedesign.entity.GameAsset;
import org.jooq.DSLContext;
import org.jooq.SQLDialect;
import org.jooq.impl.DSL;
import org.junit.jupiter.api.Test;

class GameAssetRepositoryTest {
  @Test
  void findByTenantIdConvertsJdbcTimestampAndPreservesAssetBytesAndTenantScope() throws Exception {
    try (var connection =
        DriverManager.getConnection(
            "jdbc:h2:mem:game-asset-timestamp-read;DATABASE_TO_LOWER=TRUE")) {
      DSLContext dsl = DSL.using(connection, SQLDialect.H2);
      createTable(dsl);
      LocalDateTime createdAt = LocalDateTime.of(2026, 10, 8, 21, 34, 56, 123_456_000);
      byte[] assetBytes = {0, 1, 2, -1};
      dsl.execute(
          "INSERT INTO game_assets (tenant_id, file_name, content_type, data, created_at) "
              + "VALUES (?, ?, ?, ?, ?)",
          "tenant-a",
          "map.bin",
          "application/octet-stream",
          assetBytes,
          Timestamp.valueOf(createdAt));
      dsl.execute(
          "INSERT INTO game_assets (tenant_id, file_name, content_type, data, created_at) "
              + "VALUES (?, ?, ?, ?, ?)",
          "tenant-b",
          "other.bin",
          "application/octet-stream",
          new byte[] {9},
          Timestamp.valueOf(createdAt.plusDays(1)));

      List<GameAsset> assets = new GameAssetRepository(dsl).findByTenantId("tenant-a");

      assertThat(assets).hasSize(1);
      assertThat(assets.get(0).getTenantId()).isEqualTo("tenant-a");
      assertThat(assets.get(0).getCreatedAt()).isEqualTo(createdAt);
      assertThat(assets.get(0).getData()).containsExactly(assetBytes);
    }
  }

  @Test
  void saveReadsBackTimestampAndFindByTenantIdPreservesNullTimestamp() throws Exception {
    try (var connection =
        DriverManager.getConnection(
            "jdbc:h2:mem:game-asset-save-timestamp;DATABASE_TO_LOWER=TRUE")) {
      DSLContext dsl = DSL.using(connection, SQLDialect.H2);
      createTable(dsl);
      GameAssetRepository repository = new GameAssetRepository(dsl);
      LocalDateTime createdAt = LocalDateTime.of(2026, 10, 9, 1, 2, 3, 456_789_000);
      GameAsset asset = new GameAsset();
      asset.setTenantId("tenant-a");
      asset.setFileName("map.bin");
      asset.setContentType("application/octet-stream");
      asset.setData(new byte[] {4, 5, 6});
      asset.setCreatedAt(createdAt);

      GameAsset saved = repository.save(asset);
      dsl.execute("UPDATE game_assets SET created_at = NULL WHERE id = ?", saved.getId());

      assertThat(saved.getCreatedAt()).isEqualTo(createdAt);
      assertThat(repository.findByTenantId("tenant-a"))
          .singleElement()
          .satisfies(readBack -> assertThat(readBack.getCreatedAt()).isNull());
    }
  }

  private static void createTable(DSLContext dsl) {
    dsl.execute(
        "CREATE TABLE game_assets ("
            + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
            + "tenant_id VARCHAR(36) NOT NULL, "
            + "file_name VARCHAR(255) NOT NULL, "
            + "content_type VARCHAR(255), "
            + "data BLOB, "
            + "created_at TIMESTAMP)");
  }
}
