package net.firedevops.firemud.gamedesign.repository;

import static org.assertj.core.api.Assertions.assertThat;

import java.sql.DriverManager;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import net.firedevops.firemud.gamedesign.entity.GameAsset;
import org.jooq.DSLContext;
import org.jooq.ExecuteContext;
import org.jooq.SQLDialect;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultConfiguration;
import org.jooq.impl.DefaultExecuteListener;
import org.jooq.impl.DefaultExecuteListenerProvider;
import org.junit.jupiter.api.Test;

class GameAssetRepositoryTest {
  @Test
  void insertReturnsCompletePersistedAssetReadback() throws Exception {
    try (var connection = DriverManager.getConnection("jdbc:h2:mem:game-asset-returning")) {
      List<String> executedSql = new ArrayList<>();
      DefaultConfiguration configuration = new DefaultConfiguration();
      configuration.set(connection);
      configuration.set(SQLDialect.H2);
      configuration.set(
          new DefaultExecuteListenerProvider(
              new DefaultExecuteListener() {
                @Override
                public void executeStart(ExecuteContext context) {
                  executedSql.add(context.sql());
                }
              }));
      DSLContext dsl = DSL.using(configuration);
      dsl.execute(
          "CREATE TABLE \"game_assets\" ("
              + "\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
              + "\"tenant_id\" VARCHAR(36) NOT NULL, "
              + "\"file_name\" VARCHAR(255) NOT NULL, "
              + "\"content_type\" VARCHAR(100) NOT NULL, "
              + "\"data\" BLOB NOT NULL, "
              + "\"created_at\" TIMESTAMP NOT NULL)");

      byte[] bytes = new byte[] {0, 1, 2, (byte) 0xff};
      LocalDateTime createdAt = LocalDateTime.of(2026, 10, 5, 9, 30);
      GameAsset requested = new GameAsset();
      requested.setTenantId("tenant-1");
      requested.setFileName("portrait.png");
      requested.setContentType("image/png");
      requested.setData(bytes);
      requested.setCreatedAt(createdAt);

      GameAsset saved = new GameAssetRepository(dsl).save(requested);

      assertThat(saved.getId()).isNotNull();
      assertThat(saved.getTenantId()).isEqualTo("tenant-1");
      assertThat(saved.getFileName()).isEqualTo("portrait.png");
      assertThat(saved.getContentType()).isEqualTo("image/png");
      assertThat(saved.getData()).containsExactly(bytes);
      assertThat(saved.getCreatedAt()).isEqualTo(createdAt);
      assertThat(executedSql)
          .filteredOn(sql -> sql.toLowerCase().contains("insert into \"game_assets\""))
          .singleElement()
          .satisfies(
              sql -> {
                assertThat(sql.toLowerCase()).contains("select \"id\"");
                assertThat(sql.toLowerCase()).contains("\"tenant_id\"");
                assertThat(sql.toLowerCase()).contains("\"file_name\"");
                assertThat(sql.toLowerCase()).contains("\"content_type\"");
                assertThat(sql.toLowerCase()).contains("\"data\"");
                assertThat(sql.toLowerCase()).contains("\"created_at\"");
                assertThat(sql.toLowerCase()).doesNotContain("select *");
              });
    }
  }
}
