package net.firedevops.firemud.gamedesign.repository;

import static org.assertj.core.api.Assertions.assertThat;

import java.sql.DriverManager;
import java.time.LocalDateTime;
import java.util.UUID;
import net.firedevops.firemud.gamedesign.entity.PublishAttempt;
import net.firedevops.firemud.gamedesign.model.PublishAttemptStatus;
import net.firedevops.firemud.gamedesign.model.PublishType;
import org.jooq.DSLContext;
import org.jooq.SQLDialect;
import org.jooq.impl.DSL;
import org.junit.jupiter.api.Test;

class PublishAttemptRepositoryTest {
  @Test
  void saveReturnsInsertedAttemptAndMatchesIndependentReadback() throws Exception {
    try (var connection =
        DriverManager.getConnection(
            "jdbc:h2:mem:publish-attempt-" + UUID.randomUUID() + ";DATABASE_TO_LOWER=TRUE")) {
      DSLContext dsl = DSL.using(connection, SQLDialect.H2);
      dsl.execute(
          "CREATE TABLE publish_attempt ("
              + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
              + "tenant_id VARCHAR(36) NOT NULL, publish_workflow_id VARCHAR(64) NOT NULL, "
              + "publish_type VARCHAR(32) NOT NULL, status VARCHAR(16) NOT NULL, "
              + "version_id BIGINT, version_number INT NOT NULL, "
              + "script_patch_version VARCHAR(100), base_version_id BIGINT, "
              + "request_digest VARCHAR(128), failure_code VARCHAR(64), "
              + "failure_message TEXT, created_at TIMESTAMP NOT NULL, completed_at TIMESTAMP)");

      PublishAttempt requested = new PublishAttempt();
      requested.setTenantId("tenant-publish-attempt");
      requested.setPublishWorkflowId("publish-attempt-insert-readback");
      requested.setPublishType(PublishType.FULL_VERSION);
      requested.setStatus(PublishAttemptStatus.FAILED);
      requested.setVersionId(73L);
      requested.setVersionNumber(9);
      requested.setRequestDigest("sha256:" + "a".repeat(64));
      requested.setFailureCode("PARTICIPANT_UNAVAILABLE");
      requested.setFailureMessage("full diagnostic evidence " + "x".repeat(600));
      requested.setCreatedAt(LocalDateTime.of(2026, 10, 5, 12, 30));
      requested.setCompletedAt(LocalDateTime.of(2026, 10, 5, 12, 31));

      PublishAttemptRepository repository = new PublishAttemptRepository(dsl);
      PublishAttempt saved = repository.save(requested);
      PublishAttempt independentlyRead =
          repository.findByPublishWorkflowId("publish-attempt-insert-readback").orElseThrow();

      assertThat(saved.getId()).isNotNull();
      assertThat(saved).usingRecursiveComparison().ignoringFields("id").isEqualTo(requested);
      assertThat(saved).usingRecursiveComparison().isEqualTo(independentlyRead);
      assertThat(independentlyRead.getScriptPatchVersion()).isNull();
      assertThat(independentlyRead.getBaseVersionId()).isNull();
      assertThat(independentlyRead.getFailureMessage()).hasSizeGreaterThan(512);
    }
  }
}
