package net.firedevops.firemud.gamedesign.repository;

import static org.assertj.core.api.Assertions.assertThat;

import java.sql.DriverManager;
import java.time.LocalDateTime;
import java.util.UUID;
import net.firedevops.firemud.gamedesign.entity.PublishAttemptParticipantDigest;
import net.firedevops.firemud.gamedesign.model.PublishParticipantKey;
import org.jooq.DSLContext;
import org.jooq.SQLDialect;
import org.jooq.impl.DSL;
import org.junit.jupiter.api.Test;

class PublishAttemptParticipantDigestRepositoryTest {
  @Test
  void saveReturnsAndIndependentlyReadsDedicatedAbilitySchemaDigestWithoutAggregateFallback()
      throws Exception {
    try (var connection =
        DriverManager.getConnection(
            "jdbc:h2:mem:publish-attempt-participant-digest-"
                + UUID.randomUUID()
                + ";DATABASE_TO_LOWER=TRUE")) {
      DSLContext dsl = DSL.using(connection, SQLDialect.H2);
      dsl.execute(
          "CREATE TABLE publish_attempt_participant_digest ("
              + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
              + "publish_attempt_id BIGINT NOT NULL, participant_key VARCHAR(64) NOT NULL, "
              + "scope_value VARCHAR(128) NOT NULL, base_version_id BIGINT, "
              + "applied_commit_id VARCHAR(128), content_digest VARCHAR(128), "
              + "ability_schema_digest VARCHAR(128), digest_schema_version INT, "
              + "error_code VARCHAR(64), error_message VARCHAR(512), observed_at TIMESTAMP NOT NULL)");
      PublishAttemptParticipantDigestRepository repository =
          new PublishAttemptParticipantDigestRepository(dsl);
      LocalDateTime observedAt = LocalDateTime.of(2026, 10, 5, 9, 30);

      PublishAttemptParticipantDigest gameLogicDigest = digest("GAME_LOGIC", observedAt);
      gameLogicDigest.setAbilitySchemaDigest("sha256:ability-schema-17");
      gameLogicDigest.setContentDigest("sha256:aggregate-17");
      PublishAttemptParticipantDigest savedGameLogicDigest = repository.save(gameLogicDigest);

      PublishAttemptParticipantDigest legacyDigest = digest("WORLD_MANAGEMENT", observedAt);
      legacyDigest.setContentDigest("sha256:aggregate-world-17");
      PublishAttemptParticipantDigest savedLegacyDigest = repository.save(legacyDigest);

      assertThat(savedGameLogicDigest.getAbilitySchemaDigest())
          .isEqualTo("sha256:ability-schema-17");
      assertThat(savedLegacyDigest.getAbilitySchemaDigest()).isNull();
      assertThat(repository.findByPublishAttemptId(71L))
          .extracting(PublishAttemptParticipantDigest::getParticipantKey)
          .containsExactly(
              PublishParticipantKey.GAME_LOGIC, PublishParticipantKey.WORLD_MANAGEMENT);
      assertThat(repository.findByPublishAttemptId(71L))
          .extracting(PublishAttemptParticipantDigest::getAbilitySchemaDigest)
          .containsExactly("sha256:ability-schema-17", null);
      assertThat(repository.findByPublishAttemptId(71L).get(0).getContentDigest())
          .isEqualTo("sha256:aggregate-17");
    }
  }

  private static PublishAttemptParticipantDigest digest(
      String participantKey, LocalDateTime observedAt) {
    PublishAttemptParticipantDigest digest = new PublishAttemptParticipantDigest();
    digest.setPublishAttemptId(71L);
    digest.setParticipantKey(PublishParticipantKey.valueOf(participantKey));
    digest.setScopeValue("17");
    digest.setBaseVersionId(null);
    digest.setAppliedCommitId("commit-17");
    digest.setDigestSchemaVersion(1);
    digest.setObservedAt(observedAt);
    return digest;
  }
}
