package net.firedevops.firemud.gamedesign.repository;

import static org.assertj.core.api.Assertions.assertThat;

import java.sql.DriverManager;
import java.util.ArrayList;
import java.util.List;
import net.firedevops.firemud.gamedesign.entity.VersionAssetArtifact;
import net.firedevops.firemud.gamedesign.model.VersionAssetArtifactState;
import org.jooq.DSLContext;
import org.jooq.ExecuteContext;
import org.jooq.SQLDialect;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultConfiguration;
import org.jooq.impl.DefaultExecuteListener;
import org.jooq.impl.DefaultExecuteListenerProvider;
import org.junit.jupiter.api.Test;

class VersionAssetArtifactRepositoryTest {
  @Test
  void insertReturnsDurableArtifactReadback() throws Exception {
    try (var connection =
        DriverManager.getConnection("jdbc:h2:mem:artifact-readback;DB_CLOSE_DELAY=-1")) {
      List<String> executedSql = new ArrayList<>();
      DefaultConfiguration configuration = new DefaultConfiguration();
      configuration.set(connection);
      configuration.set(SQLDialect.H2);
      configuration.set(
          new DefaultExecuteListenerProvider(
              new DefaultExecuteListener() {
                @Override
                public void executeStart(ExecuteContext context) {
                  executedSql.add(context.sql());
                }
              }));
      DSLContext dsl = DSL.using(configuration);
      dsl.execute(
          "CREATE TABLE \"version_asset_artifact\" ("
              + "\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
              + "\"tenant_id\" VARCHAR(36) NOT NULL, "
              + "\"version_id\" BIGINT NOT NULL, "
              + "\"exported_version_number\" INT NOT NULL, "
              + "\"artifact_state\" VARCHAR(64) NOT NULL, "
              + "\"state_epoch\" BIGINT NOT NULL, "
              + "\"manifest_hash\" VARCHAR(255), "
              + "\"last_workflow_id\" VARCHAR(255), "
              + "\"last_error_code\" VARCHAR(255), "
              + "\"last_error_message\" VARCHAR(1000), "
              + "\"exported_manifest_asset_keys_json\" VARCHAR(4000), "
              + "\"updated_at\" TIMESTAMP NOT NULL, "
              + "UNIQUE (\"tenant_id\", \"version_id\"))");

      VersionAssetArtifact artifact = new VersionAssetArtifact();
      artifact.setTenantId("tenant-1");
      artifact.setVersionId(7L);
      artifact.setExportedVersionNumber(3);
      artifact.setArtifactState(VersionAssetArtifactState.PUBLISHED);
      artifact.setStateEpoch(2L);
      artifact.setManifestHash("manifest-7");
      artifact.setLastWorkflowId("publish-7");
      artifact.setExportedManifestAssetKeysJson("[\"manifest.json\"]");

      VersionAssetArtifact inserted = new VersionAssetArtifactRepository(dsl).save(artifact);

      assertThat(inserted.getId()).isNotNull();
      assertThat(inserted.getTenantId()).isEqualTo("tenant-1");
      assertThat(inserted.getVersionId()).isEqualTo(7L);
      assertThat(inserted.getExportedVersionNumber()).isEqualTo(3);
      assertThat(inserted.getArtifactState()).isEqualTo(VersionAssetArtifactState.PUBLISHED);
      assertThat(inserted.getManifestHash()).isEqualTo("manifest-7");
      assertThat(inserted.getLastWorkflowId()).isEqualTo("publish-7");
      assertThat(inserted.getExportedManifestAssetKeysJson()).isEqualTo("[\"manifest.json\"]");
      assertThat(inserted.getUpdatedAt()).isNotNull();
      assertThat(executedSql)
          .filteredOn(sql -> sql.toLowerCase().contains(" where "))
          .singleElement()
          .satisfies(
              sql -> {
                assertThat(sql.toLowerCase()).contains("where \"id\" = ");
                assertThat(sql.toLowerCase()).doesNotContain("tenant_id");
                assertThat(sql.toLowerCase()).doesNotContain("version_id");
              });
    }
  }
}
