package net.firedevops.firemud.gamedesign.repository;

import static org.assertj.core.api.Assertions.assertThat;

import java.sql.DriverManager;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import net.firedevops.firemud.gamedesign.entity.VersionTemplateRemapEntry;
import net.firedevops.firemud.gamedesign.entity.VersionTemplateRemapSet;
import org.jooq.DSLContext;
import org.jooq.ExecuteContext;
import org.jooq.SQLDialect;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultConfiguration;
import org.jooq.impl.DefaultExecuteListener;
import org.jooq.impl.DefaultExecuteListenerProvider;
import org.junit.jupiter.api.Test;

class VersionTemplateRemapSetRepositoryTest {
  @Test
  void savePersistsReturnedEntryIdAndCreatedAt() throws Exception {
    try (var connection =
        DriverManager.getConnection("jdbc:h2:mem:remap-entry-returning;DB_CLOSE_DELAY=-1")) {
      List<String> executedSql = new ArrayList<>();
      DefaultConfiguration configuration = new DefaultConfiguration();
      configuration.set(connection);
      configuration.set(SQLDialect.H2);
      configuration.set(
          new DefaultExecuteListenerProvider(
              new DefaultExecuteListener() {
                @Override
                public void executeStart(ExecuteContext context) {
                  executedSql.add(context.sql());
                }
              }));
      DSLContext dsl = DSL.using(configuration);
      dsl.execute(
          "CREATE TABLE \"version_template_remap_set\" ("
              + "\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
              + "\"remap_set_id\" VARCHAR(64) NOT NULL UNIQUE, "
              + "\"tenant_id\" VARCHAR(36) NOT NULL, "
              + "\"source_version_id\" BIGINT NOT NULL, "
              + "\"target_version_id\" BIGINT NOT NULL, "
              + "\"status\" VARCHAR(32) NOT NULL, "
              + "\"created_reason\" VARCHAR(500) NOT NULL, "
              + "\"approval_reason\" VARCHAR(500), "
              + "\"created_at\" TIMESTAMP NOT NULL, "
              + "\"approved_at\" TIMESTAMP, "
              + "\"updated_at\" TIMESTAMP NOT NULL)");
      dsl.execute(
          "CREATE TABLE \"version_template_remap_entry\" ("
              + "\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
              + "\"remap_set_pk\" BIGINT NOT NULL, "
              + "\"mapping_domain\" VARCHAR(64) NOT NULL, "
              + "\"mapping_type\" VARCHAR(64) NOT NULL, "
              + "\"source_template_key\" VARCHAR(128) NOT NULL, "
              + "\"target_template_key\" VARCHAR(128) NOT NULL, "
              + "\"created_at\" TIMESTAMP NOT NULL)");

      VersionTemplateRemapEntry entry = new VersionTemplateRemapEntry();
      entry.setMappingDomain("WORLD");
      entry.setMappingType("ROOM");
      entry.setSourceTemplateKey("old-room");
      entry.setTargetTemplateKey("new-room");
      LocalDateTime entryCreatedAt = LocalDateTime.of(2026, 9, 28, 12, 30);
      entry.setCreatedAt(entryCreatedAt);

      VersionTemplateRemapSet remapSet = new VersionTemplateRemapSet();
      remapSet.setRemapSetId("remap-1");
      remapSet.setTenantId("tenant-1");
      remapSet.setSourceVersionId(1L);
      remapSet.setTargetVersionId(2L);
      remapSet.setCreatedReason("version replacement");
      remapSet.addRemapEntry(entry);

      VersionTemplateRemapSet inserted = new VersionTemplateRemapSetRepository(dsl).save(remapSet);

      assertThat(inserted.getRemapEntries())
          .singleElement()
          .satisfies(
              savedEntry -> {
                assertThat(savedEntry.getId()).isNotNull();
                assertThat(savedEntry.getCreatedAt()).isEqualTo(entryCreatedAt);
              });
      assertThat(executedSql)
          .filteredOn(
              sql -> sql.toLowerCase().contains("insert into \"version_template_remap_entry\""))
          .singleElement()
          .satisfies(
              sql -> {
                assertThat(sql.toLowerCase())
                    .contains("select \"id\", \"created_at\" from final table");
                assertThat(sql.toLowerCase()).doesNotContain("select *");
              });
    }
  }
}
