spring:
  profiles:
    active: dev
  application:
    name: game-design-service

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB:firemud}
    username: ${POSTGRES_USER:firemud}
    password: ${POSTGRES_PASSWORD:firemud}
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
