spring:
  profiles:
    active: dev
  application:
    name: game-design-service
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
