spring:
  profiles:
    active: dev
  application:
    name: social-groups-service
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true

loggingAdmin:
  host: logging-admin-service
  port: 6565
firemud:
  auth:
    jwt-secret: changemechangemechangeme123456
    jwt-expiration-ms: 3600000
  voice:
    token-expiration-ms: 300000
