syntax = "proto3";

package tcp_proxy.v1;

option java_package = "net.firedevops.firemud.tcpproxy.v1";
option java_multiple_files = true;

import "shared/v1/errors.proto";

service TcpProxyService {
  rpc Ping(PingRequest) returns (PingResponse);
  rpc NotifyDisconnect(NotifyDisconnectRequest) returns (NotifyDisconnectResponse);
}

message PingRequest {}

message PingResponse {
  string message = 1;
}

message NotifyDisconnectRequest {
  string session_id = 1;
  string tenant_id = 2;
}

message NotifyDisconnectResponse {
  shared.v1.ErrorDetail error = 1;
}
