package net.firedevops.firemud.loggingadmin.dto;

import java.time.Instant;

public record RemoteCommandCoordinatorDto(
    String coordinatorId,
    long tenantId,
    String commandId,
    String followupId,
    long originGameInstanceId,
    String originRegionId,
    long originRegionEpoch,
    long targetGameInstanceId,
    String targetRegionId,
    long targetRegionEpoch,
    Long targetDueTickId,
    Long originDeadlineRegionEpoch,
    Long originDeadlineTickId,
    String state,
    String lateResultPolicy,
    String executionOutcome,
    String gameplayResult,
    Instant updatedAt,
    String followupStatus,
    Long followupClaimedTickBatchId,
    String latestResultOutcome,
    String latestResultPayloadJson,
    Instant latestResultObservedAt,
    Long followupClaimOrdinal,
    String scriptPatchVersion,
    String pluginId,
    String pluginVersionId,
    ScriptPatchPublicationLinkDto publication,
    String playableStateScope,
    String worldSlug,
    String realmSlug,
    Long pointerVersion,
    String automationDispatchId,
    String automationWorkItemId,
    String scriptId,
    String followupPayloadKind,
    String followupRequestedCommand,
    String latestResultCommandId,
    String latestResultErrorCode,
    String targetCommandId,
    String targetCommandExecutionOutcome,
    String targetCommandGameplayResult,
    String latestResultMessage,
    PluginPublicationLinkDto pluginPublication,
    boolean followupRequiresSoloTick,
    String followupOriginSourceKind,
    String followupOriginSourceState,
    Long followupOriginSourceOrdinal,
    Long followupOriginSourceDueTickId,
    Long followupOriginSourceDueAtMs,
    String targetEntityId,
    String followupEffectKey,
    String followupFailureCode,
    String followupFailureMessage,
    String followupEventType,
    String followupEventSchemaVersion,
    String followupScriptEventId,
    String followupTriggerMode,
    String followupReadSnapshotToken,
    String followupEventPayloadJson,
    String followupClaimTargetAggregate,
    String currentOriginRuntimeRegionId,
    Long currentOriginRuntimeRegionEpoch,
    String currentTargetRuntimeRegionId,
    Long currentTargetRuntimeRegionEpoch,
    String followupQueueSourceKind,
    String followupQueueSourceState,
    Long followupQueueSourceOrdinal,
    Long followupQueueSourceDueTickId,
    Long followupQueueSourceDueAtMs,
    Long currentOriginRuntimeGameInstanceId,
    Long currentTargetRuntimeGameInstanceId,
    String currentOriginRuntimePlayableStateScope,
    String currentOriginRuntimeWorldSlug,
    String currentOriginRuntimeRealmSlug,
    Long currentOriginRuntimePointerVersion,
    String currentTargetRuntimePlayableStateScope,
    String currentTargetRuntimeWorldSlug,
    String currentTargetRuntimeRealmSlug,
    Long currentTargetRuntimePointerVersion,
    boolean originRoutingBundleStale,
    boolean targetRoutingBundleStale) {
  public record ScriptPatchPublicationLinkDto(
      String scriptPatchVersion,
      Long versionId,
      Long baseVersionId,
      String publicationState,
      Instant lastChangedAt,
      String lookupErrorCode,
      String lookupErrorMessage) {}

  public record PluginPublicationLinkDto(
      String pluginVersionId,
      Long publicationId,
      String publicationState,
      String statusReason,
      Instant lastChangedAt,
      String lookupErrorCode,
      String lookupErrorMessage) {}
}
