package net.firedevops.firemud.loggingadmin.dto;

import java.time.Instant;

public record RemoteFollowupResultDto(
    String resultId,
    long tenantId,
    String coordinatorId,
    String followupId,
    String originRegionId,
    Long originRegionEpoch,
    String targetRegionId,
    Long targetRegionEpoch,
    String outcome,
    String resultPayloadJson,
    Instant observedAt,
    String scriptPatchVersion,
    String pluginId,
    String pluginVersionId,
    ScriptPatchPublicationLinkDto publication,
    String playableStateScope,
    String worldSlug,
    String realmSlug,
    Long pointerVersion,
    String commandId,
    String automationDispatchId,
    String automationWorkItemId,
    String scriptId,
    String resultCommandId,
    String resultErrorCode,
    String resultCommandExecutionOutcome,
    String resultCommandGameplayResult,
    String resultMessage,
    PluginPublicationLinkDto pluginPublication,
    Long originDeadlineRegionEpoch,
    Long originDeadlineTickId,
    String lateResultPolicy,
    String originGameInstanceId,
    String targetGameInstanceId,
    String targetEntityId,
    String effectKey,
    String payloadKind,
    boolean requiresSoloTick,
    String originSourceKind,
    String originSourceState,
    Long originSourceOrdinal,
    Long originSourceDueTickId,
    Long originSourceDueAtMs,
    String failureCode,
    String failureMessage,
    String eventType,
    String eventSchemaVersion,
    String scriptEventId,
    String triggerMode,
    String readSnapshotToken,
    String eventPayloadJson,
    String claimTargetAggregate,
    String currentOriginRuntimeRegionId,
    Long currentOriginRuntimeRegionEpoch,
    String currentTargetRuntimeRegionId,
    Long currentTargetRuntimeRegionEpoch,
    String queueSourceKind,
    String queueSourceState,
    Long queueSourceOrdinal,
    Long queueSourceDueTickId,
    Long queueSourceDueAtMs,
    String currentOriginRuntimeGameInstanceId,
    String currentTargetRuntimeGameInstanceId,
    String currentOriginRuntimePlayableStateScope,
    String currentOriginRuntimeWorldSlug,
    String currentOriginRuntimeRealmSlug,
    Long currentOriginRuntimePointerVersion,
    String currentTargetRuntimePlayableStateScope,
    String currentTargetRuntimeWorldSlug,
    String currentTargetRuntimeRealmSlug,
    Long currentTargetRuntimePointerVersion,
    boolean originRoutingBundleStale,
    boolean targetRoutingBundleStale) {
  public record ScriptPatchPublicationLinkDto(
      String scriptPatchVersion,
      Long versionId,
      Long baseVersionId,
      String publicationState,
      Instant lastChangedAt,
      String lookupErrorCode,
      String lookupErrorMessage) {}

  public record PluginPublicationLinkDto(
      String pluginVersionId,
      Long publicationId,
      String publicationState,
      String statusReason,
      Instant lastChangedAt,
      String lookupErrorCode,
      String lookupErrorMessage) {}
}
