package net.firedevops.firemud.loggingadmin.dto;

import java.time.Instant;

public record RemoteFollowupDto(
    String followupId,
    long tenantId,
    long originGameInstanceId,
    String originRegionId,
    long originRegionEpoch,
    long targetGameInstanceId,
    String targetRegionId,
    long targetRegionEpoch,
    Long dueTickId,
    String effectKey,
    String targetEntityId,
    String status,
    String claimedTickBatchId,
    String payloadJson,
    String failureCode,
    String failureMessage,
    Instant createdAt,
    Instant updatedAt,
    Long claimOrdinal,
    String scriptPatchVersion,
    String pluginId,
    String pluginVersionId,
    ScriptPatchPublicationLinkDto publication,
    String playableStateScope,
    String worldSlug,
    String realmSlug,
    Long pointerVersion,
    String commandId,
    String automationDispatchId,
    String automationWorkItemId,
    String scriptId,
    String payloadKind,
    String requestedCommand,
    String targetCommandId,
    String targetCommandExecutionOutcome,
    String targetCommandGameplayResult,
    PluginPublicationLinkDto pluginPublication,
    boolean requiresSoloTick,
    String originSourceKind,
    String originSourceState,
    Long originSourceOrdinal,
    Long originSourceDueTickId,
    Long originSourceDueAtMs,
    Long originDeadlineRegionEpoch,
    Long originDeadlineTickId,
    String lateResultPolicy,
    String eventType,
    String eventSchemaVersion,
    String scriptEventId,
    String triggerMode,
    String readSnapshotToken,
    String eventPayloadJson,
    String claimTargetAggregate,
    String currentOriginRuntimeRegionId,
    Long currentOriginRuntimeRegionEpoch,
    String currentTargetRuntimeRegionId,
    Long currentTargetRuntimeRegionEpoch,
    String queueSourceKind,
    String queueSourceState,
    Long queueSourceOrdinal,
    Long queueSourceDueTickId,
    Long queueSourceDueAtMs,
    Long currentOriginRuntimeGameInstanceId,
    Long currentTargetRuntimeGameInstanceId,
    String currentOriginRuntimePlayableStateScope,
    String currentOriginRuntimeWorldSlug,
    String currentOriginRuntimeRealmSlug,
    Long currentOriginRuntimePointerVersion,
    String currentTargetRuntimePlayableStateScope,
    String currentTargetRuntimeWorldSlug,
    String currentTargetRuntimeRealmSlug,
    Long currentTargetRuntimePointerVersion,
    boolean originRoutingBundleStale,
    boolean targetRoutingBundleStale) {
  public record ScriptPatchPublicationLinkDto(
      String scriptPatchVersion,
      Long versionId,
      Long baseVersionId,
      String publicationState,
      Instant lastChangedAt,
      String lookupErrorCode,
      String lookupErrorMessage) {}

  public record PluginPublicationLinkDto(
      String pluginVersionId,
      Long publicationId,
      String publicationState,
      String statusReason,
      Instant lastChangedAt,
      String lookupErrorCode,
      String lookupErrorMessage) {}
}
