syntax = "proto3";

package game_logic.v1;

import "shared/v1/errors.proto";

option java_package = "net.firedevops.firemud.gamelogic.v1";
option java_multiple_files = true;

service GameLogicService {
  rpc Ping(PingRequest) returns (PingResponse);
  rpc ExecuteCommand(ExecuteCommandRequest) returns (ExecuteCommandResponse);
}

message PingRequest {}

message PingResponse {
  string message = 1;
  shared.v1.ErrorDetail error = 2;
}

message ExecuteCommandRequest {
  string tenant_id = 1;
  string session_id = 2;
  string command = 3;
}

message ExecuteCommandResponse {
  string result = 1;
  shared.v1.ErrorDetail error = 2;
}
