syntax = "proto3";

package gamedesign.v1;

import "shared/v1/errors.proto";

option java_package = "net.firedevops.firemud.gamedesign.v1";
option java_multiple_files = true;

service GameDesignService {
  rpc Ping(PingRequest) returns (PingResponse);
  rpc SaveRevision(SaveRevisionRequest) returns (SaveRevisionResponse);
  rpc PublishVersion(PublishVersionRequest) returns (PublishVersionResponse);
  rpc PublishScriptPatchVersion(PublishScriptPatchVersionRequest)
      returns (PublishScriptPatchVersionResponse);
  rpc ListVersions(ListVersionsRequest) returns (ListVersionsResponse);
}

message SaveRevisionRequest {
  string data = 1;
  int64 game_id = 2;
  int64 author_account_id = 3;
}

message SaveRevisionResponse {
  int64 revision_id = 1;
  shared.v1.ErrorDetail error = 2;
}

message PublishVersionRequest {
  int64 game_id = 1;
  string notes = 2;
}

message PublishVersionResponse {
  int64 version_id = 1;
  shared.v1.ErrorDetail error = 2;
}

message PublishScriptPatchVersionRequest {
  int64 game_id = 1;
  int64 base_version_id = 2;
  string script_patch_version = 3;
  string notes = 4;
}

message PublishScriptPatchVersionResponse {
  int64 version_id = 1;
  shared.v1.ErrorDetail error = 2;
}

message ListVersionsRequest {
  int64 game_id = 1;
}

message ListVersionsResponse {
  repeated Version versions = 1;
  shared.v1.ErrorDetail error = 2;
}

message Version {
  int64 id = 1;
  int32 version_number = 2;
  string script_patch_version = 3;
  bool is_script_only = 4;
  string notes = 5;
}

message PingRequest {}

message PingResponse {
  string message = 1;
  shared.v1.ErrorDetail error = 2;
}
