image:
  repository: firemud/account-service
  tag: latest
replicaCount: 2
resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "400m"
    memory: "512Mi"
service:
  type: ClusterIP
  port: 8080
extraEnv: {}
serviceAccount:
  create: true
  name: ""
readinessProbe:
  path: /actuator/health/readiness
  initialDelaySeconds: 5
  periodSeconds: 10
livenessProbe:
  path: /actuator/health/liveness
  initialDelaySeconds: 15
  periodSeconds: 20
affinity: {}
