CREATE TABLE game_session_tenant_scope_reservation (
    game_session_tenant_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_kind VARCHAR(32) NOT NULL,
    reserved_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_gs_tenant_scope_reservation_kind
        UNIQUE (game_session_tenant_id, reservation_kind),
    CONSTRAINT chk_gs_tenant_scope_reservation_positive
        CHECK (game_session_tenant_id > 0),
    CONSTRAINT chk_gs_tenant_scope_reservation_kind
        CHECK (reservation_kind IN ('LEGACY_OCCUPIED', 'FRESH_SOURCE_BOUND'))
);

CREATE TABLE game_session_tenant_canonical_claim (
    target_namespace VARCHAR(63) NOT NULL,
    canonical_tenant_id UUID NOT NULL,
    legacy_game_session_tenant_id BIGINT NOT NULL,
    association_kind VARCHAR(32) NOT NULL,
    reservation_kind VARCHAR(32) NOT NULL,
    association_operation_id UUID NOT NULL,
    association_request_id UUID NOT NULL,
    claimed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_gs_tenant_canonical_claim
        PRIMARY KEY (target_namespace, canonical_tenant_id),
    CONSTRAINT uq_gs_tenant_canonical_claim_private_key
        UNIQUE (target_namespace, legacy_game_session_tenant_id),
    CONSTRAINT uq_gs_tenant_canonical_claim_operation
        UNIQUE (association_operation_id),
    CONSTRAINT uq_gs_tenant_canonical_claim_request
        UNIQUE (target_namespace, association_request_id),
    CONSTRAINT uq_gs_tenant_canonical_claim_association
        UNIQUE (target_namespace, canonical_tenant_id, legacy_game_session_tenant_id,
                association_operation_id, association_kind),
    CONSTRAINT fk_gs_tenant_canonical_claim_reservation
        FOREIGN KEY (legacy_game_session_tenant_id, reservation_kind)
        REFERENCES game_session_tenant_scope_reservation
            (game_session_tenant_id, reservation_kind),
    CONSTRAINT chk_gs_tenant_canonical_claim_namespace CHECK (
        octet_length(target_namespace) BETWEEN 1 AND 63
        AND target_namespace ~ '^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$'
    ),
    CONSTRAINT chk_gs_tenant_canonical_claim_uuid
        CHECK (canonical_tenant_id <> '00000000-0000-0000-0000-000000000000'::UUID),
    CONSTRAINT chk_gs_tenant_canonical_claim_ids CHECK (
        legacy_game_session_tenant_id > 0
        AND association_operation_id <> '00000000-0000-0000-0000-000000000000'::UUID
        AND association_request_id <> '00000000-0000-0000-0000-000000000000'::UUID
    ),
    CONSTRAINT chk_gs_tenant_canonical_claim_kind CHECK (
        (association_kind = 'RETAINED_V8_1' AND reservation_kind = 'LEGACY_OCCUPIED')
        OR
        (association_kind = 'FRESH_SOURCE_BOUND' AND reservation_kind = 'FRESH_SOURCE_BOUND')
    )
);

CREATE TABLE game_session_fresh_tenant_association (
    association_operation_id UUID PRIMARY KEY,
    target_namespace VARCHAR(63) NOT NULL,
    association_request_id UUID NOT NULL,
    source_schema_version INTEGER NOT NULL,
    source_target_namespace VARCHAR(63) NOT NULL,
    source_request_id UUID NOT NULL,
    source_canonical_tenant_id UUID NOT NULL,
    canonical_tenant_id UUID NOT NULL,
    legacy_game_session_tenant_id BIGINT NOT NULL,
    source_game_row_id BIGINT NOT NULL,
    source_game_tenant_key VARCHAR(72) NOT NULL,
    provenance_kind VARCHAR(32) NOT NULL,
    association_kind VARCHAR(32) NOT NULL DEFAULT 'FRESH_SOURCE_BOUND',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_gs_fresh_tenant_association_request
        UNIQUE (target_namespace, association_request_id),
    CONSTRAINT uq_gs_fresh_tenant_association_canonical
        UNIQUE (target_namespace, canonical_tenant_id),
    CONSTRAINT uq_gs_fresh_tenant_association_private_key
        UNIQUE (legacy_game_session_tenant_id),
    CONSTRAINT fk_gs_fresh_tenant_association_reservation
        FOREIGN KEY (legacy_game_session_tenant_id, association_kind)
        REFERENCES game_session_tenant_scope_reservation
            (game_session_tenant_id, reservation_kind),
    CONSTRAINT fk_gs_fresh_tenant_association_claim
        FOREIGN KEY (target_namespace, canonical_tenant_id, legacy_game_session_tenant_id,
                     association_operation_id, association_kind)
        REFERENCES game_session_tenant_canonical_claim
            (target_namespace, canonical_tenant_id, legacy_game_session_tenant_id,
             association_operation_id, association_kind),
    CONSTRAINT chk_gs_fresh_tenant_association_identity CHECK (
        octet_length(target_namespace) BETWEEN 1 AND 63
        AND target_namespace ~ '^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$'
        AND source_target_namespace = target_namespace
        AND source_schema_version = 1
        AND source_request_id = association_request_id
        AND source_canonical_tenant_id = canonical_tenant_id
        AND association_operation_id <> '00000000-0000-0000-0000-000000000000'::UUID
        AND association_request_id <> '00000000-0000-0000-0000-000000000000'::UUID
        AND source_request_id <> '00000000-0000-0000-0000-000000000000'::UUID
        AND canonical_tenant_id <> '00000000-0000-0000-0000-000000000000'::UUID
    ),
    CONSTRAINT chk_gs_fresh_tenant_association_source CHECK (
        legacy_game_session_tenant_id > 0
        AND source_game_row_id > 0
        AND char_length(source_game_tenant_key) BETWEEN 1 AND 72
        AND source_game_tenant_key !~ '^[[:space:]]*$'
        AND provenance_kind = 'NEW_GAME_ROW'
        AND association_kind = 'FRESH_SOURCE_BOUND'
    )
);

-- [jooq ignore start]
CREATE FUNCTION reject_game_session_tenant_owner_evidence_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'Game Session tenant owner evidence is immutable'
        USING ERRCODE = 'check_violation';
END;
$$;

CREATE TRIGGER game_session_tenant_scope_reservation_immutable
    BEFORE UPDATE OR DELETE ON game_session_tenant_scope_reservation
    FOR EACH ROW EXECUTE FUNCTION reject_game_session_tenant_owner_evidence_mutation();
CREATE TRIGGER game_session_tenant_scope_reservation_no_truncate
    BEFORE TRUNCATE ON game_session_tenant_scope_reservation
    FOR EACH STATEMENT EXECUTE FUNCTION reject_game_session_tenant_owner_evidence_mutation();
CREATE TRIGGER game_session_tenant_canonical_claim_immutable
    BEFORE UPDATE OR DELETE ON game_session_tenant_canonical_claim
    FOR EACH ROW EXECUTE FUNCTION reject_game_session_tenant_owner_evidence_mutation();
CREATE TRIGGER game_session_tenant_canonical_claim_no_truncate
    BEFORE TRUNCATE ON game_session_tenant_canonical_claim
    FOR EACH STATEMENT EXECUTE FUNCTION reject_game_session_tenant_owner_evidence_mutation();
CREATE TRIGGER game_session_fresh_tenant_association_immutable
    BEFORE UPDATE OR DELETE ON game_session_fresh_tenant_association
    FOR EACH ROW EXECUTE FUNCTION reject_game_session_tenant_owner_evidence_mutation();
CREATE TRIGGER game_session_fresh_tenant_association_no_truncate
    BEFORE TRUNCATE ON game_session_fresh_tenant_association
    FOR EACH STATEMENT EXECUTE FUNCTION reject_game_session_tenant_owner_evidence_mutation();

CREATE FUNCTION reserve_game_session_tenant_scope()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    current_kind VARCHAR(32);
BEGIN
    IF TG_OP = 'UPDATE' AND NEW.tenant_id IS NOT DISTINCT FROM OLD.tenant_id THEN
        RETURN NEW;
    END IF;
    IF NEW.tenant_id IS NULL THEN
        RETURN NEW;
    END IF;
    IF NEW.tenant_id <= 0 THEN
        RAISE EXCEPTION 'Game Session tenant scope must be positive'
            USING ERRCODE = '23514', CONSTRAINT = 'chk_gs_tenant_scope_reservation_positive';
    END IF;

    INSERT INTO game_session_tenant_scope_reservation
        (game_session_tenant_id, reservation_kind)
    VALUES (NEW.tenant_id, 'LEGACY_OCCUPIED')
    ON CONFLICT (game_session_tenant_id) DO NOTHING;

    SELECT reservation_kind
      INTO current_kind
      FROM game_session_tenant_scope_reservation
     WHERE game_session_tenant_id = NEW.tenant_id
     FOR KEY SHARE;
    IF current_kind IS DISTINCT FROM 'LEGACY_OCCUPIED' THEN
        RAISE EXCEPTION 'Numeric-only tenant scope cannot use a fresh source-bound key'
            USING ERRCODE = '23514', CONSTRAINT = 'chk_gs_numeric_fresh_tenant_scope_denied';
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION claim_retained_game_session_tenant_identity()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    current_kind VARCHAR(32);
BEGIN
    INSERT INTO game_session_tenant_scope_reservation
        (game_session_tenant_id, reservation_kind)
    VALUES (NEW.legacy_game_session_tenant_id, 'LEGACY_OCCUPIED')
    ON CONFLICT (game_session_tenant_id) DO NOTHING;

    SELECT reservation_kind
      INTO current_kind
      FROM game_session_tenant_scope_reservation
     WHERE game_session_tenant_id = NEW.legacy_game_session_tenant_id
     FOR KEY SHARE;
    IF current_kind IS DISTINCT FROM 'LEGACY_OCCUPIED' THEN
        RAISE EXCEPTION 'Retained tenant mapping cannot claim a fresh source-bound key'
            USING ERRCODE = '23514', CONSTRAINT = 'chk_gs_retained_fresh_tenant_scope_denied';
    END IF;

    INSERT INTO game_session_tenant_canonical_claim
        (target_namespace, canonical_tenant_id, legacy_game_session_tenant_id,
         association_kind, reservation_kind, association_operation_id, association_request_id)
    VALUES
        (NEW.target_namespace, NEW.canonical_tenant_id, NEW.legacy_game_session_tenant_id,
         'RETAINED_V8_1', 'LEGACY_OCCUPIED', NEW.operation_id, NEW.association_request_id)
    ON CONFLICT DO NOTHING;

    IF NOT EXISTS (
        SELECT 1
          FROM game_session_tenant_canonical_claim
         WHERE target_namespace = NEW.target_namespace
           AND canonical_tenant_id = NEW.canonical_tenant_id
           AND legacy_game_session_tenant_id = NEW.legacy_game_session_tenant_id
           AND association_kind = 'RETAINED_V8_1'
           AND reservation_kind = 'LEGACY_OCCUPIED'
           AND association_operation_id = NEW.operation_id
           AND association_request_id = NEW.association_request_id
    ) THEN
        RAISE EXCEPTION 'Retained tenant mapping conflicts with a Game Session owner claim'
            USING ERRCODE = '23505', CONSTRAINT = 'pk_gs_tenant_canonical_claim';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER game_session_retained_association_claim
    BEFORE INSERT ON game_session_retained_tenant_association
    FOR EACH ROW EXECUTE FUNCTION claim_retained_game_session_tenant_identity();

DO $$
DECLARE
    scope_table RECORD;
    scope_count INTEGER := 0;
    max_reserved_tenant BIGINT;
    identity_sequence TEXT;
BEGIN
    FOR scope_table IN
        SELECT column_info.table_name
          FROM information_schema.columns column_info
          JOIN information_schema.tables table_info
            ON table_info.table_schema = column_info.table_schema
           AND table_info.table_name = column_info.table_name
         WHERE column_info.table_schema = current_schema()
           AND column_info.column_name = 'tenant_id'
           AND table_info.table_type = 'BASE TABLE'
         GROUP BY column_info.table_name
         ORDER BY column_info.table_name
    LOOP
        scope_count := scope_count + 1;
        EXECUTE format(
            'CREATE TRIGGER reserve_game_session_tenant_scope '
                || 'BEFORE INSERT OR UPDATE ON %I '
                || 'FOR EACH ROW EXECUTE FUNCTION reserve_game_session_tenant_scope()',
            scope_table.table_name);
        EXECUTE format(
            'INSERT INTO game_session_tenant_scope_reservation '
                || '(game_session_tenant_id, reservation_kind) '
                || 'SELECT DISTINCT tenant_id, ''LEGACY_OCCUPIED'' FROM %I '
                || 'WHERE tenant_id IS NOT NULL '
                || 'ON CONFLICT (game_session_tenant_id) DO NOTHING',
            scope_table.table_name);
        EXECUTE format(
            'ALTER TABLE %I ADD CONSTRAINT fk_tenant_scope_reservation '
                || 'FOREIGN KEY (tenant_id) REFERENCES game_session_tenant_scope_reservation '
                || '(game_session_tenant_id) NOT VALID',
            scope_table.table_name);
        EXECUTE format(
            'ALTER TABLE %I VALIDATE CONSTRAINT fk_tenant_scope_reservation',
            scope_table.table_name);
    END LOOP;

    IF scope_count = 0 THEN
        RAISE EXCEPTION 'No Game Session tenant scope tables were found';
    END IF;

    INSERT INTO game_session_tenant_scope_reservation
        (game_session_tenant_id, reservation_kind)
    SELECT DISTINCT legacy_game_session_tenant_id, 'LEGACY_OCCUPIED'
      FROM game_session_retained_tenant_association
    ON CONFLICT (game_session_tenant_id) DO NOTHING;

    ALTER TABLE game_session_retained_tenant_association
        ADD CONSTRAINT fk_gs_retained_tenant_reservation
        FOREIGN KEY (legacy_game_session_tenant_id)
        REFERENCES game_session_tenant_scope_reservation (game_session_tenant_id) NOT VALID;
    ALTER TABLE game_session_retained_tenant_association
        VALIDATE CONSTRAINT fk_gs_retained_tenant_reservation;

    INSERT INTO game_session_tenant_canonical_claim
        (target_namespace, canonical_tenant_id, legacy_game_session_tenant_id,
         association_kind, reservation_kind, association_operation_id, association_request_id)
    SELECT target_namespace, canonical_tenant_id, legacy_game_session_tenant_id,
           'RETAINED_V8_1', 'LEGACY_OCCUPIED', operation_id, association_request_id
      FROM game_session_retained_tenant_association
    ON CONFLICT DO NOTHING;

    IF EXISTS (
        SELECT 1
          FROM game_session_retained_tenant_association retained
         WHERE NOT EXISTS (
             SELECT 1
               FROM game_session_tenant_canonical_claim claim
              WHERE claim.target_namespace = retained.target_namespace
                AND claim.canonical_tenant_id = retained.canonical_tenant_id
                AND claim.legacy_game_session_tenant_id = retained.legacy_game_session_tenant_id
                AND claim.association_kind = 'RETAINED_V8_1'
                AND claim.reservation_kind = 'LEGACY_OCCUPIED'
                AND claim.association_operation_id = retained.operation_id
                AND claim.association_request_id = retained.association_request_id
         )
    ) THEN
        RAISE EXCEPTION 'Retained Game Session identity could not be claimed exactly';
    END IF;

    SELECT max(game_session_tenant_id)
      INTO max_reserved_tenant
      FROM game_session_tenant_scope_reservation;
    identity_sequence := pg_get_serial_sequence(
        'game_session_tenant_scope_reservation', 'game_session_tenant_id');
    IF identity_sequence IS NULL THEN
        RAISE EXCEPTION 'Game Session tenant reservation identity sequence is unavailable';
    ELSIF max_reserved_tenant IS NULL THEN
        PERFORM setval(identity_sequence, 1, FALSE);
    ELSE
        PERFORM setval(identity_sequence, max_reserved_tenant, TRUE);
    END IF;
END;
$$;
-- [jooq ignore stop]
