package net.firedevops.firemud.gamesession.entity;

import java.time.Instant;
import lombok.Data;

@Data
public class RemoteFollowup {
  private Long id;
  private String followupId;
  private Long tenantId;
  private Long originGameInstanceId;
  private String originRegionId;
  private long originRegionEpoch;
  private Long targetGameInstanceId;
  private String targetRegionId;
  private long targetRegionEpoch;
  private long dueTickId;
  private String effectKey;
  private String targetEntityId;
  private String claimTargetAggregate;
  private String status;
  private String claimedTickBatchId;
  private Long claimOrdinal;
  private String queueSourceKind;
  private String queueSourceState;
  private Long queueSourceOrdinal;
  private Long queueSourceDueTickId;
  private Long queueSourceDueAtMs;
  private String payloadJson;
  private String payloadKind;
  private String requestedCommand;
  private boolean requiresSoloTick;
  private String originSourceKind;
  private String originSourceState;
  private Long originSourceOrdinal;
  private Long originSourceDueTickId;
  private Long originSourceDueAtMs;
  private String eventType;
  private String eventSchemaVersion;
  private String scriptEventId;
  private String triggerMode;
  private String readSnapshotToken;
  private String eventPayloadJson;
  private String failureCode;
  private String failureMessage;
  private String playableStateScope;
  private String worldSlug;
  private String realmSlug;
  private Long pointerVersion;
  private String scriptPatchVersion;
  private Long scriptPinEpoch;
  private String sourceScriptPatchVersion;
  private Long sourceScriptPinEpoch;
  private String sourceScriptPinControlPlaneRequestId;
  private String targetScriptPatchVersion;
  private Long targetScriptPinEpoch;
  private String targetScriptPinControlPlaneRequestId;
  private String pluginId;
  private String pluginVersionId;
  private String commandId;
  private String automationDispatchId;
  private String automationWorkItemId;
  private String scriptId;
  private Instant createdAt;
  private Instant updatedAt;
}
