ALTER TABLE zone ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 0;
ALTER TABLE room ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 0;
ALTER TABLE instance ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 0;
ALTER TABLE instance ADD COLUMN expires_at TIMESTAMP;

