#!/usr/bin/env python3
"""Validate canonical workflow tool and runtime authorities."""

from __future__ import annotations

import json
import os
import re
import subprocess
import tempfile
from collections import Counter
from pathlib import Path

import yaml


def main() -> int:
    root = Path(os.environ.get("FIREMUD_REPO_ROOT", Path(__file__).resolve().parents[2]))
    workflows = root / ".github/workflows"
    actions = root / ".github/actions"

    def fail(m):
        raise SystemExit(m)

    def authority(path):
        out = {}
        for line in path.read_text().splitlines():
            if not line or line.startswith("#"):
                continue
            if not re.fullmatch(r"[A-Z][A-Z0-9_]*=[A-Za-z0-9._:-]+", line):
                fail(f"{path}: invalid authority line: {line}")
            k, v = line.split("=", 1)
            if k in out:
                fail(f"{path}: duplicate {k}")
            out[k] = v
        return out

    node = (root / ".node-version").read_text().strip()
    if not re.fullmatch(r"24\.\d+\.\d+", node):
        fail(".node-version must pin an exact Node 24 release")
    python = (root / ".python-version").read_text().strip()
    if not re.fullmatch(r"3\.14\.\d+", python):
        fail(".python-version must pin an exact Python 3.14 release")
    requirements_profiles = {
        "yaml": root / "config/python/yaml-requirements.txt",
        "ci": root / "config/python/ci-requirements.txt",
        "smoke": root / "config/python/smoke-requirements.txt",
        "docs": root / "config/docs/requirements.txt",
    }
    requirements_inputs = {
        "yaml": root / "config/python/yaml-requirements.in",
        "ci": root / "config/python/ci-requirements.in",
        "smoke": root / "config/python/smoke-requirements.in",
    }
    expected_lock_header = f"# This file is autogenerated by pip-compile with Python {'.'.join(python.split('.')[:2])}"
    for path in requirements_profiles.values():
        if expected_lock_header not in path.read_text().splitlines()[:8]:
            fail(f"{path} must be generated with Python {python}")
    expected_compile_commands = {
        "yaml": "--output-file=config/python/yaml-requirements.txt config/python/yaml-requirements.in",
        "ci": "--output-file=config/python/ci-requirements.txt config/python/ci-requirements.in",
        "smoke": "--output-file=config/python/smoke-requirements.txt config/python/smoke-requirements.in",
    }
    expected_direct_requirements = {
        "yaml": {"pyyaml"},
        "ci": {"pathspec", "ruff", "yamllint"},
        "smoke": {"websocket-client"},
    }
    for name, path in requirements_inputs.items():
        if not path.is_file() or not path.read_text().strip():
            fail(f"{path} must define unlocked direct requirements")
        direct_requirements = {
            line.strip().lower()
            for line in path.read_text().splitlines()
            if line.strip() and not line.lstrip().startswith("#") and not line.startswith("-r ")
        }
        input_includes = [line.strip() for line in path.read_text().splitlines() if line.strip().startswith("-r ")]
        if input_includes != (["-r yaml-requirements.in"] if name == "ci" else []):
            fail(f"{path} must use the canonical YAML input relationship")
        if direct_requirements != expected_direct_requirements[name]:
            fail(f"{path} does not match its canonical direct dependencies")
        lock_text = requirements_profiles[name].read_text()
        if not any(expected_compile_commands[name] in line for line in lock_text.splitlines()[:8]):
            fail(f"{requirements_profiles[name]} must record regeneration from {path.name}")
    requirement_line = re.compile(r"(?i)^([a-z0-9][a-z0-9_.-]*)==([^=\s\\]+)\s*\\?$")
    hash_line = re.compile(r"^--hash=sha256:[0-9a-f]{64}\s*\\?$")

    def read_lock(path):
        entries = {}
        current = None
        includes = []
        for raw in path.read_text().splitlines():
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            if line.startswith("-r "):
                includes.append(line[3:])
                continue
            match = requirement_line.fullmatch(line)
            if match:
                current = match.group(1).lower()
                if current in entries:
                    fail(f"{path}: duplicate pinned dependency: {current}")
                entries[current] = [match.group(2), 0]
                continue
            if hash_line.fullmatch(line):
                if current is None:
                    fail(f"{path}: hash is not attached to a pinned dependency")
                entries[current][1] += 1
                continue
            fail(f"{path}: invalid hashed lock line: {raw}")
        if not entries:
            fail(f"{path} must contain at least one pinned dependency")
        missing = [name for name, (version, hashes) in entries.items() if hashes == 0]
        if missing:
            fail(f"{path}: dependencies lack hashes: {', '.join(sorted(missing))}")
        return entries, includes

    locks = {name: read_lock(path) for name, path in requirements_profiles.items()}
    for name, (entries, includes) in locks.items():
        if includes:
            fail(f"{name} requirements must not include another profile")
    for dependency, (version, _) in locks["yaml"][0].items():
        if locks["ci"][0].get(dependency, (None,))[0] != version:
            fail(f"ci requirements must resolve the canonical YAML dependency: {dependency}")

    ap = root / "config/workflow-tool-versions.env"
    a = authority(ap)
    versions = ["KUBECTL", "HELM", "GH", "BUF", "KUBECONFORM", "VELERO", "ACTIONLINT", "TRIVY", "LYCHEE", "ORT", "ZAP"]
    if any(not re.fullmatch(r"\d+\.\d+\.\d+", a.get(f"{x}_VERSION", "")) for x in versions):
        fail("all workflow tools must have exact versions")
    pairs = {
        "KUBECTL": "KUBECTL_LINUX_AMD64",
        "HELM": "HELM_LINUX_AMD64",
        "GH": "GH_LINUX_AMD64",
        "BUF": "BUF_LINUX_X86_64",
        "KUBECONFORM": "KUBECONFORM_LINUX_AMD64",
        "VELERO": "VELERO_LINUX_AMD64",
        "TRIVY": "TRIVY_LINUX_AMD64",
        "LYCHEE": "LYCHEE_LINUX_X86_64_MUSL",
    }
    for tool, stem in pairs.items():
        if a.get(f"{stem}_CHECKSUM_VERSION") != a[f"{tool}_VERSION"]:
            fail(f"{tool} checksum version is stale")
        if not re.fullmatch(r"[0-9a-f]{64}", a.get(f"{stem}_SHA256", "")):
            fail(f"{tool} checksum is invalid")
    for tool in ("VELERO_IMAGE", "ORT", "ZAP"):
        if not re.fullmatch(r"sha256:[0-9a-f]{64}", a.get(f"{tool}_DIGEST", "")):
            fail(f"{tool} digest is invalid")
    expected = (
        {f"{x}_VERSION" for x in versions}
        | {f"{s}_{suffix}" for s in pairs.values() for suffix in ("CHECKSUM_VERSION", "SHA256")}
        | {"VELERO_IMAGE_DIGEST", "ORT_DIGEST", "ZAP_DIGEST"}
    )
    if set(a) != expected:
        fail("workflow tool authority has unexpected or missing keys")

    loader = yaml.safe_load((actions / "load-workflow-tool-versions/action.yml").read_text())
    loader_runs = [
        step.get("run")
        for step in loader.get("runs", {}).get("steps", [])
        if isinstance(step, dict) and isinstance(step.get("run"), str)
    ]
    if len(loader_runs) != 1:
        fail("workflow authority loader must define exactly one validation script")
    loader_run = loader_runs[0]
    expected_loader_outputs = {
        "kubectl-version",
        "kubectl-linux-amd64-sha256",
        "helm-version",
        "helm-linux-amd64-sha256",
        "gh-version",
        "gh-linux-amd64-sha256",
        "buf-version",
        "buf-linux-x86-64-sha256",
        "kubeconform-version",
        "kubeconform-linux-amd64-sha256",
        "velero-version",
        "velero-linux-amd64-sha256",
        "actionlint-version",
        "trivy-version",
        "trivy-linux-amd64-sha256",
        "lychee-version",
        "lychee-linux-x86-64-musl-sha256",
        "ort-image",
        "zap-image",
    }
    if set(loader.get("outputs", {})) != expected_loader_outputs:
        fail("workflow authority loader outputs are unexpected or incomplete")
    for output in expected_loader_outputs:
        output_definition = loader["outputs"][output]
        if not isinstance(output_definition, dict) or not isinstance(output_definition.get("description"), str):
            fail(f"workflow authority loader output is missing a description: {output}")
        if not output_definition["description"].strip():
            fail(f"workflow authority loader output description is empty: {output}")
        value = output_definition.get("value") if isinstance(output_definition, dict) else None
        if value != "${{ steps.versions.outputs." + output + " }}":
            fail(f"workflow authority loader output is not sourced from validation: {output}")
    with tempfile.TemporaryDirectory() as temporary:
        workspace = Path(temporary) / "workspace"
        workspace.mkdir()
        authority_path = workspace / "config"
        authority_path.mkdir()
        output_path = Path(temporary) / "github-output"
        output_path.write_text("sentinel\n")
        env = {**os.environ, "GITHUB_WORKSPACE": str(workspace), "GITHUB_OUTPUT": str(output_path)}
        (authority_path / "workflow-tool-versions.env").write_text(ap.read_text())
        canonical = subprocess.run(
            ["bash", "-c", loader_run], cwd=temporary, env=env, capture_output=True, text=True, check=False
        )
        if canonical.returncode != 0:
            fail(f"workflow authority loader rejects canonical authority: {canonical.stderr.strip()}")
        (authority_path / "workflow-tool-versions.env").write_bytes(
            ap.read_bytes().rstrip(b"\r\n") + b"\nACTIONLINT_VERSION=0.0.0"
        )
        output_path.write_text("sentinel\n")
        eof_duplicate = subprocess.run(
            ["bash", "-c", loader_run], cwd=temporary, env=env, capture_output=True, text=True, check=False
        )
        if eof_duplicate.returncode == 0:
            fail("workflow authority loader accepts a duplicate final line without a newline")
        if output_path.read_text() != "sentinel\n":
            fail("duplicate final authority assignment can mutate workflow outputs")
        (authority_path / "workflow-tool-versions.env").write_text(ap.read_text() + " \t  \n# harmless comment\n")
        whitespace = subprocess.run(
            ["bash", "-c", loader_run], cwd=temporary, env=env, capture_output=True, text=True, check=False
        )
        if whitespace.returncode != 0:
            fail(f"workflow authority loader rejects whitespace-only lines: {whitespace.stderr.strip()}")
        (authority_path / "workflow-tool-versions.env").write_text(
            ap.read_text() + "GITHUB_OUTPUT=redirected.output\nnot a key=value\n"
        )
        output_path.write_text("sentinel\n")
        unsupported = subprocess.run(
            ["bash", "-c", loader_run], cwd=temporary, env=env, capture_output=True, text=True, check=False
        )
        if unsupported.returncode == 0:
            fail("workflow authority loader accepts unsupported assignments")
        if output_path.read_text() != "sentinel\n" or (Path(temporary) / "redirected.output").exists():
            fail("unsupported authority assignment can redirect workflow outputs")
        (authority_path / "workflow-tool-versions.env").write_text(ap.read_text() + "KUBECTL_VERSION=0.0.0\n")
        output_path.write_text("sentinel\n")
        duplicate = subprocess.run(
            ["bash", "-c", loader_run], cwd=temporary, env=env, capture_output=True, text=True, check=False
        )
        if duplicate.returncode == 0:
            fail("workflow authority loader accepts duplicate supported assignments")
        if output_path.read_text() != "sentinel\n":
            fail("duplicate supported authority assignment can mutate workflow outputs")
        missing_key_text = "\n".join(
            line for line in ap.read_text().splitlines() if not line.startswith("ACTIONLINT_VERSION=")
        )
        (authority_path / "workflow-tool-versions.env").write_text(missing_key_text + "\n")
        output_path.write_text("sentinel\n")
        missing_key_env = {**env, "ACTIONLINT_VERSION": a["ACTIONLINT_VERSION"]}
        missing_key = subprocess.run(
            ["bash", "-c", loader_run],
            cwd=temporary,
            env=missing_key_env,
            capture_output=True,
            text=True,
            check=False,
        )
        if missing_key.returncode == 0:
            fail("workflow authority loader accepts a missing key supplied by the ambient environment")
        if output_path.read_text() != "sentinel\n":
            fail("missing workflow authority key can mutate workflow outputs")

    def load(path):
        d = yaml.safe_load(path.read_text())
        return d if isinstance(d, dict) else {}

    def run_has_gh(run):
        return bool(re.search(r"(^|[;&|()\s])gh(?:\s|$)", run))

    executable_helper_suffixes = {".cjs", ".js", ".py", ".sh"}

    def is_executable_helper(path):
        if path.suffix in executable_helper_suffixes:
            return True
        try:
            if path.is_file() and path.stat().st_mode & 0o111:
                return True
            with path.open(encoding="utf-8", errors="ignore") as stream:
                return stream.readline().startswith("#!")
        except OSError:
            return False

    def references(text):
        explicit_reference_pattern = re.compile(
            r"(?:^|[;&|()\s])(?:(?:/usr/bin/)?(?:bash|sh|dash|zsh|ksh|python|python3)"
            r"(?:\s+-[A-Za-z0-9][A-Za-z0-9_-]*)*(?:\s+--)?|source|\.)\s+"
            r"(?P<quote>['\"])?(?:\./)?"
            r"(?P<path>(?:dev-tools|services)/[A-Za-z0-9_./-]+)"
            r"(?(quote)(?P=quote)|(?![A-Za-z0-9_./'\"-]))",
            flags=re.MULTILINE,
        )
        explicitly_invoked = {
            root / match.group("path") for match in explicit_reference_pattern.finditer(text)
        }
        result = set()
        for name in re.findall(r"(?:\./)?((?:dev-tools|services)/[A-Za-z0-9_./-]+)", text):
            path = root / name.rstrip("\"'")
            if path.is_file() and (path in explicitly_invoked or is_executable_helper(path)):
                result.add(path)
        return result

    referenced_file_cache = {}

    def helper_text(text, seen=None):
        seen = set() if seen is None else seen
        parts = [text]
        for path in references(text):
            if path in seen:
                continue
            seen.add(path)
            if path not in referenced_file_cache:
                referenced_file_cache[path] = path.read_text(errors="ignore")
            source = referenced_file_cache[path]
            parts.extend(helper_text(source, seen))
        return parts

    workflow_expansion_cache = {}

    def expand_text(text):
        if text not in workflow_expansion_cache:
            workflow_expansion_cache[text] = "\n".join(helper_text(text))
        return workflow_expansion_cache[text]

    conditional_contract_profile = (
        "${{ (needs.changes.outputs.lightweight_only == 'true' && "
        "needs.changes.outputs.design_docs_changed == 'true' && "
        "needs.changes.outputs.validation_python_changed != 'true') && 'yaml' || 'ci' }}"
    )

    def setup_python_profile(path, step, *, allow_conditional=False):
        with_input = step.get("with", {})
        if not isinstance(with_input, dict):
            fail(f"{path}: setup-python with input must be a mapping")
        profile = with_input.get("requirements", "none")
        valid_profiles = {"yaml", "ci", "smoke", "docs", "none"}
        if allow_conditional:
            valid_profiles.add(conditional_contract_profile)
        if not isinstance(profile, str) or profile not in valid_profiles:
            fail(f"{path}: invalid Python dependency profile")
        return profile

    def composite_python_profile(uses):
        if not uses.startswith("./.github/actions/"):
            return None
        action_path = root / uses[2:] / "action.yml"
        if not action_path.is_file():
            return None
        action = yaml.safe_load(action_path.read_text(encoding="utf-8")) or {}
        for step in action.get("runs", {}).get("steps", []):
            if not isinstance(step, dict) or step.get("uses") != "./.github/actions/setup-python":
                continue
            return setup_python_profile(action_path, step)
        return None

    for composite in (
        "./.github/actions/download-validated-preview-artifact",
        "./.github/actions/resolve-certificate-identity-mode",
    ):
        if composite_python_profile(composite) != "yaml":
            fail(f"{composite} must expose its canonical YAML Python profile")

    def python_needs(expanded_text):
        if not re.search(r"(^|[;&|()\s])(?:/usr/bin/)?python3?(?:\s|$)", expanded_text):
            return None
        if re.search(r"(^|\n)\s*import websocket\b", expanded_text):
            return "smoke"
        if re.search(r"(^|[;&|\s])(ruff|yamllint)(?:\s|$)", expanded_text):
            return "ci"
        if re.search(r"(^|\n)\s*(?:import|from) yaml\b", expanded_text):
            return "yaml"
        if re.search(r"(^|[;&|\s])(?:python3 -m )?mkdocs(?:\s|$)", expanded_text):
            return "docs"
        return "none"

    def has_gh_consumer(expanded_text):
        return run_has_gh(expanded_text)

    def validate_composite_steps(path, steps):
        setup_profiles = set()
        setup_gh = False
        for step in steps:
            if not isinstance(step, dict):
                continue
            uses = str(step.get("uses", ""))
            run = str(step.get("run", ""))
            expanded_text = expand_text(run)
            need = python_needs(expanded_text)
            gh_consumer = has_gh_consumer(expanded_text)
            if uses == "./.github/actions/setup-python":
                setup_profiles.add(setup_python_profile(path, step))
            elif path.parent.name == "setup-python" and uses.startswith("actions/setup-python@"):
                setup_profiles.add("none")
            setup_gh |= uses == "./.github/actions/setup-gh"
            if uses.startswith("actions/setup-python@") and path.parent.name != "setup-python":
                fail(f"{path}: bypasses setup-python wrapper")
            if need is not None:
                if not setup_profiles:
                    fail(f"{path}: Python consumer lacks setup")
                if need != "none":
                    compatible_profiles = {"yaml", "ci"} if need == "yaml" else {need}
                    if not setup_profiles.intersection(compatible_profiles):
                        fail(f"{path}: Python consumer lacks its pinned dependency profile")
            if gh_consumer and not setup_gh:
                fail(f"{path}: gh consumer lacks setup")

    if python_needs(expand_text("bash ./dev-tools/tests/dev-tools-readme-contract.sh")) == "smoke":
        fail("documentation/data references must not imply the smoke dependency profile")
    if python_needs(expand_text("bash ./services/game-session-service/websocket-login-look-smoke.sh")) != "smoke":
        fail("invoked WebSocket smoke helper must retain the smoke dependency profile")

    with tempfile.TemporaryDirectory(prefix="workflow-authority-", dir=root / "dev-tools") as helper_dir:
        helper_relative = Path(helper_dir).relative_to(root).as_posix()
        ignored = subprocess.run(
            ["git", "check-ignore", "--quiet", "--no-index", "--", f"{helper_relative}/extensionless-helper"],
            cwd=root,
            capture_output=True,
            text=True,
            check=False,
        )
        if ignored.returncode != 0:
            fail("workflow authority fixtures must be ignored under dev-tools")
        helper = Path(helper_dir) / "extensionless-helper"
        shebang_helper = Path(helper_dir) / "shebang-helper"
        suffix_helper = Path(helper_dir) / "other-suffix.bash"
        data = Path(helper_dir) / "extensionless-data"
        executable_data = Path(helper_dir) / "extensionless-executable-data"
        invoked = Path(helper_dir) / "extensionless-invoked"
        invoked_suffix = Path(helper_dir) / "invoked.bash"
        python_smoke_helper = Path(helper_dir) / "python-smoke-helper"
        composite_python_helper = Path(helper_dir) / "composite-python-helper"
        composite_none_helper = Path(helper_dir) / "composite-none-helper"
        composite_gh_helper = Path(helper_dir) / "composite-gh-helper"
        helper.write_text("# option terminator helper\n", encoding="utf-8")
        shebang_helper.write_text("#!/usr/bin/env bash\n# extensionless helper\n", encoding="utf-8")
        suffix_helper.write_text("#!/usr/bin/env bash\n# suffix helper\n", encoding="utf-8")
        data.write_text("extensionless data\n", encoding="utf-8")
        executable_data.write_text("extensionless executable data\n", encoding="utf-8")
        invoked.write_text("# explicit interpreter helper\n", encoding="utf-8")
        invoked_suffix.write_text("# explicit interpreter suffix helper\n", encoding="utf-8")
        python_smoke_helper.write_text("import websocket\n", encoding="utf-8")
        composite_python_helper.write_text("python3 - <<'PY'\nimport websocket\nPY\n", encoding="utf-8")
        composite_none_helper.write_text("python3 - <<'PY'\nprint('dependency free')\nPY\n", encoding="utf-8")
        composite_gh_helper.write_text("gh --version\n", encoding="utf-8")
        executable_data.chmod(0o755)
        helper_reference = f"bash -- ./{helper.relative_to(root).as_posix()}"
        shebang_reference = f"bash ./{shebang_helper.relative_to(root).as_posix()}"
        suffix_reference = f"bash ./{suffix_helper.relative_to(root).as_posix()}"
        data_reference = f"documentation mentions ./{data.relative_to(root).as_posix()}"
        invoked_reference = f"bash ./{invoked.relative_to(root).as_posix()}"
        invoked_suffix_reference = f"python3 ./{invoked_suffix.relative_to(root).as_posix()}"
        python_smoke_reference = f"python ./{python_smoke_helper.relative_to(root).as_posix()}"
        sourced_reference = f"source ./{invoked.relative_to(root).as_posix()}"
        dotted_reference = f". ./{invoked_suffix.relative_to(root).as_posix()}"
        quoted_invoked_reference = f"bash './{invoked.relative_to(root).as_posix()}'"
        quoted_terminated_reference = f"bash -e -- './{invoked.relative_to(root).as_posix()}'"
        quoted_invoked_suffix_reference = f'python3 "./{invoked_suffix.relative_to(root).as_posix()}"'
        quoted_sourced_reference = f"source './{invoked.relative_to(root).as_posix()}'"
        quoted_dotted_reference = f'. "./{invoked_suffix.relative_to(root).as_posix()}"'
        mismatched_quote_reference = f"bash './{invoked.relative_to(root).as_posix()}\""
        executable_data_reference = f"bash ./{executable_data.relative_to(root).as_posix()}"
        composite_python_reference = f"bash ./{composite_python_helper.relative_to(root).as_posix()}"
        composite_none_reference = f"bash ./{composite_none_helper.relative_to(root).as_posix()}"
        composite_gh_reference = f"bash ./{composite_gh_helper.relative_to(root).as_posix()}"
        if helper not in references(helper_reference):
            fail("extensionless helper after an option terminator was not detected")
        if "# option terminator helper" not in expand_text(helper_reference):
            fail("extensionless helper after an option terminator was not expanded")
        if shebang_helper not in references(shebang_reference):
            fail("extensionless helper with a shebang was not detected")
        if "# extensionless helper" not in expand_text(shebang_reference):
            fail("extensionless helper with a shebang was not expanded")
        if suffix_helper not in references(suffix_reference):
            fail("helper with an unlisted suffix and a shebang was not detected")
        if data in references(data_reference):
            fail("extensionless data without an invocation was treated as an executable helper")
        if invoked not in references(invoked_reference):
            fail("extensionless helper passed to an explicit interpreter was not detected")
        if "# explicit interpreter helper" not in expand_text(invoked_reference):
            fail("extensionless helper passed to an explicit interpreter was not expanded")
        if invoked_suffix not in references(invoked_suffix_reference):
            fail("helper with an unlisted suffix passed to an explicit interpreter was not detected")
        if python_needs(expand_text(python_smoke_reference)) != "smoke":
            fail("invoked Python helper must retain the smoke dependency profile")
        if invoked not in references(quoted_invoked_reference):
            fail("quoted extensionless helper passed to bash was not detected")
        if invoked not in references(quoted_terminated_reference):
            fail("quoted extensionless helper after an option terminator was not detected")
        if invoked_suffix not in references(quoted_invoked_suffix_reference):
            fail("quoted helper with an unlisted suffix passed to Python was not detected")
        if invoked not in references(sourced_reference):
            fail("extensionless helper sourced without a shebang was not detected")
        if invoked_suffix not in references(dotted_reference):
            fail("helper with an unlisted suffix dot-sourced without a shebang was not detected")
        if invoked not in references(quoted_sourced_reference):
            fail("quoted extensionless helper sourced without a shebang was not detected")
        if invoked_suffix not in references(quoted_dotted_reference):
            fail("quoted helper with an unlisted suffix dot-sourced without a shebang was not detected")
        if invoked in references(mismatched_quote_reference):
            fail("explicit helper invocation accepts mismatched quote delimiters")
        if executable_data not in references(executable_data_reference):
            fail("extensionless executable file was not detected")
        if "extensionless executable data" not in expand_text(executable_data_reference):
            fail("extensionless executable file was not expanded")

        composite_fixture = root / ".github/actions/workflow-authority-fixture/action.yml"

        validate_composite_steps(composite_fixture, ["malformed YAML step"])

        def expect_composite_failure(steps, expected_message):
            try:
                validate_composite_steps(composite_fixture, steps)
            except SystemExit as error:
                if expected_message not in str(error):
                    fail(f"composite fixture failed for an unexpected reason: {error}")
            else:
                fail(f"composite fixture unexpectedly passed: {expected_message}")

        python_steps = [{"run": composite_python_reference}]
        expect_composite_failure(python_steps, "Python consumer lacks setup")
        expect_composite_failure(
            [{"uses": "./.github/actions/setup-python", "with": {"requirements": "none"}}, *python_steps],
            "Python consumer lacks its pinned dependency profile",
        )
        validate_composite_steps(
            composite_fixture,
            [
                {"uses": "./.github/actions/setup-python", "with": {"requirements": "smoke"}},
                {"uses": "./.github/actions/setup-python", "with": {"requirements": "none"}},
                *python_steps,
            ],
        )
        none_steps = [{"run": composite_none_reference}]
        expect_composite_failure(none_steps, "Python consumer lacks setup")
        validate_composite_steps(
            composite_fixture,
            [{"uses": "./.github/actions/setup-python", "with": {"requirements": "smoke"}}, *none_steps],
        )
        validate_composite_steps(
            composite_fixture,
            [{"uses": "./.github/actions/setup-python", "with": {"requirements": "yaml"}}, *none_steps],
        )
        gh_steps = [{"run": composite_gh_reference}]
        expect_composite_failure(gh_steps, "gh consumer lacks setup")
        validate_composite_steps(composite_fixture, [{"uses": "./.github/actions/setup-gh"}, *gh_steps])

    workflow_paths = sorted((*workflows.glob("*.yml"), *workflows.glob("*.yaml")))

    expected_permissions = {
        "weekly-security-scan.yml": {"contents": "read"},
        "manual-backup-restore.yml": {"contents": "read"},
        "release-notes.yml": {"contents": "read"},
    }
    for name, permissions in expected_permissions.items():
        workflow = load(workflows / name)
        if workflow.get("permissions") != permissions:
            fail(f"{name} must define exact top-level permissions: {permissions}")

    license_workflow = load(workflows / "license-scan.yml")
    license_changes = (license_workflow.get("jobs") or {}).get("changes")
    if not isinstance(license_changes, dict):
        fail("license-scan.yml changes job is missing")
    license_filter_steps = [
        step
        for step in license_changes.get("steps", [])
        if isinstance(step, dict)
        and step.get("id") == "filter"
        and str(step.get("uses", "")).startswith("dorny/paths-filter@")
    ]
    if len(license_filter_steps) != 1:
        fail("license-scan.yml must define exactly one dorny paths filter step")
    license_filter_with = license_filter_steps[0].get("with")
    if not isinstance(license_filter_with, dict):
        fail("license-scan.yml dorny paths filter must define with mapping")
    license_filter = license_filter_with.get("filters")
    if not isinstance(license_filter, str):
        fail("license-scan.yml dorny paths filter must define filters YAML")
    license_filter_data = yaml.safe_load(license_filter)
    if not isinstance(license_filter_data, dict):
        fail("license-scan.yml dorny filters YAML must be a mapping")
    for group in ("gradle", "npm"):
        paths = license_filter_data.get(group)
        if not isinstance(paths, list):
            fail(f"license-scan.yml {group} filter must be a path list")
        for authority_path in (".node-version",):
            if paths.count(authority_path) != 1:
                fail(f"license-scan.yml {group} filter must contain exactly one {authority_path}")
        if "config/workflow-tool-versions.env" in paths:
            fail(f"license-scan.yml {group} filter must not match the entire tool authority file")

    node_count = python_count = gh_count = 0
    for path in workflow_paths:
        for job_name, job in (load(path).get("jobs") or {}).items():
            if not isinstance(job, dict):
                continue
            checkout = py = gh_setup_seen = loader = False
            python_profiles = set()
            for step in job.get("steps", []):
                if not isinstance(step, dict):
                    continue
                uses = str(step.get("uses", ""))
                run = str(step.get("run", ""))
                if uses.startswith("actions/checkout@"):
                    checkout = True
                if uses == "./.github/actions/load-workflow-tool-versions":
                    if not checkout:
                        fail(f"{path.name}:{job_name}: loader before checkout")
                    loader = True
                if uses.startswith("actions/setup-node@"):
                    node_count += 1
                    if (
                        not checkout
                        or step.get("with", {}).get("node-version-file") != ".node-version"
                        or "node-version" in step.get("with", {})
                    ):
                        fail(f"{path.name}:{job_name}: invalid Node authority consumption")
                if uses.startswith("actions/setup-python@"):
                    fail(f"{path.name}:{job_name}: bypasses canonical setup-python action")
                if uses == "./.github/actions/setup-python":
                    python_count += 1
                    if not checkout:
                        fail(f"{path.name}:{job_name}: Python setup before checkout")
                    py = True
                    selected_profile = setup_python_profile(
                        f"{path.name}:{job_name}",
                        step,
                        allow_conditional=path.name == "ci.yml" and job_name == "dev-tool-contract-checks",
                    )
                    python_profiles.add(selected_profile)
                composite_profile = composite_python_profile(uses)
                if composite_profile is not None:
                    py = True
                    python_profiles.add(composite_profile)
                if uses == "./.github/actions/setup-gh":
                    gh_count += 1
                    if not checkout:
                        fail(f"{path.name}:{job_name}: gh setup before checkout")
                    gh_setup_seen = True
                expanded_text = expand_text(run)
                need = python_needs(expanded_text)
                if need is not None and not py:
                    fail(f"{path.name}:{job_name}: direct or helper Python consumer uses ambient runner Python")
                if need == "yaml" and not python_profiles.intersection({"yaml", "ci", conditional_contract_profile}):
                    fail(f"{path.name}:{job_name}: PyYAML helper lacks its pinned dependency profile")
                if (
                    need in {"smoke", "ci", "docs"}
                    and need not in python_profiles
                    and conditional_contract_profile not in python_profiles
                ):
                    fail(f"{path.name}:{job_name}: {need} helper lacks its pinned dependency profile")
                if has_gh_consumer(expanded_text) and not gh_setup_seen:
                    fail(f"{path.name}:{job_name}: direct or helper gh consumer is not preceded by canonical setup-gh")
                if uses.startswith("oss-review-toolkit/ort-ci-github-action@") and (
                    not loader
                    or step.get("with", {}).get("image") != "${{ steps.workflow-tool-versions.outputs.ort-image }}"
                ):
                    fail(f"{path.name}:{job_name}: ORT bypasses authority")
    if not min(node_count, python_count, gh_count):
        fail("expected Node, Python, and gh consumers")

    dev_demo = load(workflows / "dev-demo.yml")
    deploy_steps = (dev_demo.get("jobs") or {}).get("dev-demo-deploy", {}).get("steps", [])
    cluster_access_indexes = [
        index
        for index, step in enumerate(deploy_steps)
        if isinstance(step, dict) and step.get("id") == "cluster-access"
    ]
    gh_setup_indexes = [
        index
        for index, step in enumerate(deploy_steps)
        if isinstance(step, dict) and step.get("name") == "Set up canonical GitHub CLI"
    ]
    if len(cluster_access_indexes) != 1 or len(gh_setup_indexes) != 1:
        fail("dev-demo must define exactly one cluster access check and canonical gh setup")
    cluster_access_index = cluster_access_indexes[0]
    gh_setup_index = gh_setup_indexes[0]
    if gh_setup_index != cluster_access_index + 1:
        fail("dev-demo canonical gh setup must immediately follow cluster access verification")
    gh_setup = deploy_steps[gh_setup_index]
    if gh_setup.get("if") != "${{ steps.cluster-access.outputs.available == 'true' }}":
        fail("dev-demo canonical gh setup must require available cluster access")
    for index, step in enumerate(deploy_steps):
        if (
            isinstance(step, dict)
            and has_gh_consumer(expand_text(str(step.get("run", ""))))
            and index <= gh_setup_index
        ):
            fail("dev-demo gh consumer must follow canonical gh setup")

    publisher = load(workflows / "publish-pr-runtime-images.yml")["jobs"]["publish"]
    if publisher.get("permissions", {}).get("contents") != "read":
        fail("trusted publisher checkout requires contents: read")

    for path in sorted(actions.glob("*/action.yml")):
        validate_composite_steps(path, load(path).get("runs", {}).get("steps", []))

    text = "\n".join(p.read_text() for p in workflow_paths)
    for forbidden in (
        "python-version:",
        "ruff==",
        "PyYAML\n",
        "websocket-client\n",
        "aquasecurity/trivy/main",
        "aquasecurity/setup-trivy@",
        "aquasecurity/trivy-action@",
        "zaproxy:stable",
        "VELERO_VERSION=v",
        'KUBECONFORM_VERSION="v',
        f"BUF_VERSION: '{a['BUF_VERSION']}'",
    ):
        if forbidden in text:
            fail(f"workflow contains stale or duplicated authority: {forbidden}")
    workflow_authority_requirements = {
        "ci.yml": (
            "buf-version",
            "buf-linux-x86-64-sha256",
            "kubeconform-version",
            "kubeconform-linux-amd64-sha256",
            "actionlint-version",
        ),
        "docs.yml": ("lychee-version",),
        "manual-backup-restore.yml": ("velero-version", "velero-linux-amd64-sha256"),
        "security.yml": ("uses: ./.github/actions/setup-trivy",),
        "weekly-security-scan.yml": ("uses: ./.github/actions/setup-trivy",),
        "zap-baseline.yml": ("zap-image",),
    }
    for name, needles in workflow_authority_requirements.items():
        data = (workflows / name).read_text()
        if any(n not in data for n in needles):
            fail(f"{name} does not consume all canonical tool outputs")

    manual_backup_restore_text = (workflows / "manual-backup-restore.yml").read_text()
    velero_curl_pattern = (
        r"(?m)^\s*curl -fsSL --retry 3 --retry-delay 2 --retry-max-time 30 \\\n"
        r"\s*--connect-timeout 10 --max-time 60 \\\n"
        r'\s*"https://github\.com/vmware-tanzu/velero/releases/download/v\$\{VELERO_VERSION\}/\$\{archive\}" \\\n'
        r'\s*-o "\$archive"$'
    )
    if len(re.findall(velero_curl_pattern, manual_backup_restore_text)) != 1:
        fail(
            "manual-backup-restore.yml must define exactly one Velero installer with canonical bounded retries and timeouts"
        )

    ci_text = (workflows / "ci.yml").read_text()
    buf_curl_pattern = (
        r"(?m)^\s*curl -fsSL --retry 3 --retry-delay 2 --retry-max-time 30 \\\n"
        r"\s*--connect-timeout 10 --max-time 60 \\\n"
        r'\s*"https://github\.com/bufbuild/buf/releases/download/v\$\{BUF_VERSION\}/buf-Linux-x86_64" \\\n'
        r"\s*-o /tmp/buf$"
    )
    if len(re.findall(buf_curl_pattern, ci_text)) != 1:
        fail("ci.yml must define exactly one Buf installer with canonical bounded retries and timeouts")
    for required_buf_fragment in (
        "BUF_VERSION: ${{ steps.workflow-tool-versions.outputs.buf-version }}",
        "BUF_SHA256: ${{ steps.workflow-tool-versions.outputs.buf-linux-x86-64-sha256 }}",
        'echo "${BUF_SHA256}  /tmp/buf" | sha256sum --check --status',
    ):
        if required_buf_fragment not in ci_text:
            fail(f"ci.yml Buf installer does not consume canonical authority: {required_buf_fragment}")

    kubeconform_curl_pattern = (
        r"(?m)^\s*curl -fsSL --retry 3 --retry-delay 2 --retry-max-time 30 --connect-timeout 10 --max-time 60 "
        r'"https://github\.com/yannh/kubeconform/releases/download/v\$\{KUBECONFORM_VERSION\}/kubeconform-linux-amd64\.tar\.gz" '
        r"-o /tmp/kubeconform\.tgz$"
    )
    if len(re.findall(kubeconform_curl_pattern, ci_text)) != 1:
        fail("ci.yml must define exactly one kubeconform installer with canonical bounded retries and timeouts")
    for required_kubeconform_fragment in (
        "KUBECONFORM_VERSION: ${{ steps.workflow-tool-versions.outputs.kubeconform-version }}",
        "KUBECONFORM_SHA256: ${{ steps.workflow-tool-versions.outputs.kubeconform-linux-amd64-sha256 }}",
        'echo "${KUBECONFORM_SHA256}  /tmp/kubeconform.tgz" | sha256sum --check --status',
    ):
        if required_kubeconform_fragment not in ci_text:
            fail(f"ci.yml kubeconform installer does not consume canonical authority: {required_kubeconform_fragment}")

    setup_gh_text = (actions / "setup-gh/action.yml").read_text()
    setup_gh_curl_pattern = (
        r"(?m)^\s*curl -fsSL --retry 3 --retry-delay 2 --retry-max-time 30 \\\n"
        r"\s*--connect-timeout 10 --max-time 60 \\\n"
        r'\s*"https://github\.com/cli/cli/releases/download/v\$\{gh_version\}/gh_\$\{gh_version\}_linux_amd64\.tar\.gz" \\\n'
        r'\s*-o "\$temporary_archive"$'
    )
    if len(re.findall(setup_gh_curl_pattern, setup_gh_text)) != 1:
        fail("setup-gh must define exactly one installer with canonical bounded retries and timeouts")
    for required_setup_gh_fragment in (
        "GH_VERSION: ${{ steps.versions.outputs.gh-version }}",
        "GH_SHA256: ${{ steps.versions.outputs.gh-linux-amd64-sha256 }}",
        'printf \'%s  %s\\n\' "$gh_sha256" "$temporary_archive"',
        'printf \'%s  %s\\n\' "$gh_sha256" "$archive_path"',
    ):
        if required_setup_gh_fragment not in setup_gh_text:
            fail(f"setup-gh installer does not consume canonical authority: {required_setup_gh_fragment}")

    setup_kubectl_text = (actions / "setup-kubectl/action.yml").read_text()
    if "azure/setup-kubectl@" in setup_kubectl_text or "actions/cache@" in setup_kubectl_text:
        fail("setup-kubectl must use a direct, non-cached installer")
    kubectl_curl_pattern = (
        r"(?m)^\s*curl -fsSL --retry 3 --retry-delay 2 --retry-max-time 30 \\\n"
        r"\s*--connect-timeout 10 --max-time 60 \\\n"
        r'\s*"https://dl\.k8s\.io/release/v\$\{kubectl_version\}/bin/linux/amd64/kubectl" \\\n'
        r'\s*-o "\$temporary_binary"$'
    )
    if len(re.findall(kubectl_curl_pattern, setup_kubectl_text)) != 1:
        fail("setup-kubectl must define exactly one direct installer with canonical bounded retries and timeouts")
    for required_setup_kubectl_fragment in (
        "KUBECTL_VERSION: ${{ steps.versions.outputs.kubectl-version }}",
        "KUBECTL_SHA256: ${{ steps.versions.outputs.kubectl-linux-amd64-sha256 }}",
        "RUNNER_OS",
        "RUNNER_ARCH",
        "requires a Linux X64 runner",
        'printf \'%s  %s\\n\' "$kubectl_sha256" "$temporary_binary"',
        "sha256sum --check --status",
        "install -m 0755",
        "GITHUB_PATH",
    ):
        if required_setup_kubectl_fragment not in setup_kubectl_text:
            fail(
                f"setup-kubectl installer does not consume canonical authority safely: {required_setup_kubectl_fragment}"
            )
    if (
        'kubectl_root="${RUNNER_TEMP:?}/firemud-kubectl"' not in setup_kubectl_text
        or 'installation_directory="$kubectl_root/$kubectl_version"' not in setup_kubectl_text
    ):
        fail("setup-kubectl must use a stable versioned installation directory under RUNNER_TEMP")
    if 'temporary_directory="$(mktemp -d "$kubectl_root/.tmp.XXXXXX")"' not in setup_kubectl_text:
        fail("setup-kubectl must keep per-invocation temporary files under its stable root")
    if 'mv -fT -- "$staged_binary" "$installed_binary"' not in setup_kubectl_text:
        fail("setup-kubectl must atomically replace the verified binary")
    if "trap cleanup EXIT" not in setup_kubectl_text or 'rm -rf -- "$temporary_directory"' not in setup_kubectl_text:
        fail("setup-kubectl must clean only its exact temporary directory")

    setup_trivy_text = (actions / "setup-trivy/action.yml").read_text()
    if "aquasecurity/setup-trivy@" in setup_trivy_text or "aquasecurity/trivy-action@" in setup_trivy_text:
        fail("setup-trivy must use a repository-owned direct installer")
    for required_setup_trivy_fragment in (
        "TRIVY_VERSION: ${{ steps.versions.outputs.trivy-version }}",
        "TRIVY_SHA256: ${{ steps.versions.outputs.trivy-linux-amd64-sha256 }}",
        "RUNNER_OS",
        "RUNNER_ARCH",
        "requires a Linux X64 runner",
        "https://github.com/aquasecurity/trivy/releases/download/",
        "trivy_${trivy_version}_Linux-64bit.tar.gz",
        "sha256sum --check --status",
        'tar -xzf "$archive" -C "$temporary_directory" trivy',
        "install -m 0755",
        "GITHUB_PATH",
    ):
        if required_setup_trivy_fragment not in setup_trivy_text:
            fail(
                f"setup-trivy installer does not consume canonical authority safely: {required_setup_trivy_fragment}"
            )

    release = load(workflows / "release-notes.yml")
    if release.get("permissions") != {"contents": "read"}:
        fail("release-notes.yml must define read-only top-level permissions")
    release_jobs = release.get("jobs") or {}
    generator = release_jobs.get("generate-release-notes")
    release_publisher = release_jobs.get("publish-release")
    if not isinstance(generator, dict) or not isinstance(release_publisher, dict):
        fail("release-notes.yml must define generator and publish jobs")
    if generator.get("permissions") != {"contents": "read"}:
        fail("release generator must remain contents read-only")
    if release_publisher.get("permissions") != {"contents": "write"}:
        fail("release publisher must have only contents write")
    if release_publisher.get("needs") != "generate-release-notes":
        fail("release publisher must depend on generated assets")
    generator_steps = generator.get("steps", [])
    publisher_steps = release_publisher.get("steps", [])
    upload_steps = [
        step
        for step in generator_steps
        if isinstance(step, dict) and re.fullmatch(r"actions/upload-artifact@[0-9a-f]{40}", str(step.get("uses", "")))
    ]
    if len(upload_steps) != 1:
        fail("release generator must upload exactly one release artifact")
    upload_with = upload_steps[0].get("with") or {}
    if upload_with.get("name") != "release-assets" or upload_with.get("path") != "build/release-assets":
        fail("release generator must upload only build/release-assets")
    download_steps = [
        step
        for step in publisher_steps
        if isinstance(step, dict) and re.fullmatch(r"actions/download-artifact@[0-9a-f]{40}", str(step.get("uses", "")))
    ]
    if len(download_steps) != 1:
        fail("release publisher must download exactly one pinned release artifact")
    download_with = download_steps[0].get("with") or {}
    if download_with.get("name") != "release-assets" or download_with.get("path") != "build/release-assets":
        fail("release publisher must consume the release-assets handoff")
    harden_steps = [
        step
        for step in publisher_steps
        if isinstance(step, dict)
        and re.fullmatch(r"step-security/harden-runner@[0-9a-f]{40}", str(step.get("uses", "")))
    ]
    if len(harden_steps) != 1:
        fail("release publisher must define exactly one pinned harden-runner action")
    checkout_steps = [
        step
        for step in publisher_steps
        if isinstance(step, dict) and str(step.get("uses", "")).startswith("actions/checkout@")
    ]
    if len(checkout_steps) != 1:
        fail("release publisher must define exactly one checkout")
    checkout_with = checkout_steps[0].get("with") or {}
    if checkout_with.get("ref") != "${{ github.event.repository.default_branch }}":
        fail("release publisher checkout must use the trusted default branch")
    if checkout_with.get("persist-credentials") is not False:
        fail("release publisher checkout must disable persisted credentials")
    checkout_index = next(index for index, step in enumerate(publisher_steps) if step is checkout_steps[0])
    setup_gh_indexes = [
        index
        for index, step in enumerate(publisher_steps)
        if isinstance(step, dict) and step.get("uses") == "./.github/actions/setup-gh"
    ]
    if len(setup_gh_indexes) != 1:
        fail("release publisher must use canonical setup-gh exactly once")
    if checkout_index >= setup_gh_indexes[0]:
        fail("release publisher must check out the trusted default branch before setup-gh")
    mutation = re.compile(r"\bgh\s+release\s+(?:create|edit|upload)\b")
    for step in generator_steps:
        if isinstance(step, dict) and mutation.search(str(step.get("run", ""))):
            fail("release mutation must not run in the read-only generator")
    if not any(mutation.search(str(step.get("run", ""))) for step in publisher_steps if isinstance(step, dict)):
        fail("release publisher must own gh release mutation")
    generator_text = "\n".join(str(step.get("run", "")) for step in generator_steps if isinstance(step, dict))
    for required_release_behavior in (
        "generate_notice.py",
        "assemble_licenses_dir.py",
        "zip -r",
        "gh release view",
        "publishedAt",
    ):
        if required_release_behavior not in generator_text:
            fail(f"release generator lost existing behavior: {required_release_behavior}")
    publisher_text = "\n".join(str(step.get("run", "")) for step in publisher_steps if isinstance(step, dict))
    for asset in (
        "firemud-${{ github.ref_name }}-licenses.zip",
        "firemud-${{ github.ref_name }}-release-compliance.zip",
        "build/release-assets/NOTICE.md#NOTICE.md",
    ):
        if asset not in publisher_text:
            fail(f"release publisher lost asset name: {asset}")

    ci_jobs = load(workflows / "ci.yml").get("jobs") or {}
    frontend_checks = ci_jobs.get("frontend-checks")
    if not isinstance(frontend_checks, dict):
        fail("ci.yml frontend-checks job is missing")
    frontend_steps = frontend_checks.get("steps")
    if not isinstance(frontend_steps, list):
        fail("ci.yml frontend-checks steps are missing")
    cache_lockfiles = {
        "cache-openapi": "config/openapi/package-lock.json",
        "cache-web-client": "web-client/package-lock.json",
    }
    for cache_id, lockfile in cache_lockfiles.items():
        matches = [step for step in frontend_steps if isinstance(step, dict) and step.get("id") == cache_id]
        if len(matches) != 1:
            fail(f"ci.yml frontend-checks must define exactly one {cache_id} step")
        with_data = matches[0].get("with")
        key = with_data.get("key") if isinstance(with_data, dict) else None
        hash_match = re.search(r"hashFiles\(([^)]*)\)", key) if isinstance(key, str) else None
        paths = re.findall(r"['\"]([^'\"]+)['\"]", hash_match.group(1)) if hash_match else []
        if set(paths) != {".node-version", lockfile}:
            fail(f"ci.yml {cache_id} key must hash .node-version and {lockfile}")

    velero_manifest = (root / "k8s/velero/verify-backups-cronjob.yaml").read_text()
    velero_images = re.findall(r"image: velero/velero:[^\s]+", velero_manifest)
    allowed_velero_images = {
        f"image: velero/velero:v{a['VELERO_VERSION']}",
        f"image: velero/velero:v{a['VELERO_VERSION']}@{a['VELERO_IMAGE_DIGEST']}",
    }
    if len(velero_images) != 1 or velero_images[0] not in allowed_velero_images:
        fail("Velero image version/digest projection is stale")

    renovate = json.loads((root / "renovate.json").read_text())
    if not {"nodenv", "pyenv", "pip_requirements", "custom.regex"} <= set(renovate["enabledManagers"]):
        fail("Renovate managers incomplete")
    custom_managers = renovate.get("customManagers", [])
    if len(custom_managers) != 3:
        fail("Renovate must define version, Velero image, and ORT/ZAP image authority managers")

    def translate_renovate_pattern(pattern_source):
        return re.sub(r"\(\?<([A-Za-z_])", r"(?P<\1", pattern_source)

    unsupported_re2_tokens = ("(?<=", "(?<!", "(?=", "(?!")

    def uses_unsupported_re2_lookaround(pattern_source):
        return any(token in pattern_source for token in unsupported_re2_tokens)

    def compile_re2_pattern(pattern_source):
        if uses_unsupported_re2_lookaround(pattern_source):
            fail("Renovate custom manager matchStrings uses unsupported RE2 lookaround")
        return re.compile(translate_renovate_pattern(pattern_source))

    for token in unsupported_re2_tokens:
        try:
            compile_re2_pattern(f"{token}a")
        except SystemExit as error:
            if "unsupported RE2 lookaround" not in str(error):
                fail(f"Renovate contract rejected {token} with an unexpected diagnostic")
        else:
            fail(f"Renovate contract accepted unsupported RE2 token: {token}")
    synthetic_pattern = compile_re2_pattern(r"prefix-(?<capture>[A-Z]+)")
    synthetic_match = synthetic_pattern.search("prefix-A")
    if synthetic_match is None or synthetic_match.group("capture") != "A":
        fail("Renovate pattern translation must preserve named captures")
    expected_dep_names = {
        "KUBECTL": "kubernetes/kubernetes",
        "HELM": "helm/helm",
        "GH": "cli/cli",
        "BUF": "bufbuild/buf",
        "KUBECONFORM": "yannh/kubeconform",
        "ACTIONLINT": "rhysd/actionlint",
        "TRIVY": "aquasecurity/trivy",
        "LYCHEE": "lycheeverse/lychee",
    }
    expected_image_dep_names = {
        "VELERO": "velero/velero",
        "ORT": "ghcr.io/oss-review-toolkit/ort",
        "ZAP": "ghcr.io/zaproxy/zaproxy",
    }
    expected_renovate_dependencies = Counter(
        (expected_dep_names[x], a[f"{x}_VERSION"]) for x in expected_dep_names
    )
    expected_renovate_dependencies.update(
        (expected_image_dep_names[x], a[f"{x}_VERSION"]) for x in expected_image_dep_names
    )
    matched = Counter()
    velero_image_managers = [
        manager for manager in custom_managers if manager.get("depNameTemplate") == "velero/velero"
    ]
    if len(velero_image_managers) != 1:
        fail("Renovate must define exactly one Velero image manager")
    velero_image_manager = velero_image_managers[0]
    if (
        velero_image_manager.get("autoReplaceStringTemplate")
        != "# renovate-image: datasource=docker depName=velero/velero\nVELERO_VERSION={{{replace '^v' '' newValue}}}\nVELERO_IMAGE_DIGEST={{{newDigest}}}"
    ):
        fail("Velero image manager must atomically replace its version and digest using supported fields")
    if velero_image_manager.get("matchStringsStrategy", "any") != "any":
        fail("Velero image manager must expose one complete authority-block match")
    if velero_image_manager.get("currentValueTemplate") != "v{{{currentValue}}}":
        fail("Velero image manager must expose a v-prefixed current value")
    if any(
        unsupported in velero_image_manager["autoReplaceStringTemplate"]
        for unsupported in ("authorityPrefix", "authoritySuffix")
    ):
        fail("Velero image manager must not reference unsupported custom capture groups")
    docker_managers = [manager for manager in custom_managers if manager.get("versioningTemplate") == "docker"]
    if len(docker_managers) != 2:
        fail("Renovate must define separate Velero and ORT/ZAP Docker managers")
    ort_zap_image_managers = [manager for manager in docker_managers if manager is not velero_image_manager]
    if len(ort_zap_image_managers) != 1:
        fail("Renovate must define exactly one ORT/ZAP image manager")
    ort_zap_image_manager = ort_zap_image_managers[0]
    if "currentValueTemplate" in ort_zap_image_manager or "autoReplaceStringTemplate" in ort_zap_image_manager:
        fail("ORT/ZAP image manager must not inherit Velero value or replacement templates")
    authority_text = ap.read_text()
    velero_pattern_sources = velero_image_manager.get("matchStrings") or []
    if len(velero_pattern_sources) != 1:
        fail("Velero image manager must define one atomic version-and-digest match pattern")
    try:
        velero_pattern = compile_re2_pattern(velero_pattern_sources[0])
    except (re.error, TypeError) as error:
        fail(f"Velero image manager pattern is invalid: {error}")
    velero_matches = list(velero_pattern.finditer(authority_text))
    if len(velero_matches) != 1:
        fail("Velero image manager must match exactly one atomic version-and-digest block")
    velero_match = velero_matches[0]
    if "vmware-tanzu/velero" in authority_text:
        fail("workflow tool authority must not retain the stale vmware-tanzu/velero marker")
    if velero_match.group("currentValue") != a["VELERO_VERSION"]:
        fail("Velero image manager must match the authority image version")
    if velero_match.group("currentDigest") != a["VELERO_IMAGE_DIGEST"]:
        fail("Velero image manager must match the authority image digest")
    new_velero_value = "v9.9.9"
    new_velero_digest = "sha256:" + "b" * 64
    def render_velero_template(template):
        rendered = template.replace("{{{newDigest}}}", new_velero_digest)
        rendered = rendered.replace(
            "{{{replace '^v' '' newValue}}}", re.sub(r"^v", "", new_velero_value)
        )
        return rendered

    replacement = render_velero_template(velero_image_manager["autoReplaceStringTemplate"])
    expected_replacement = velero_match.group(0).replace(
        f"VELERO_VERSION={a['VELERO_VERSION']}", "VELERO_VERSION=9.9.9"
    ).replace(a["VELERO_IMAGE_DIGEST"], new_velero_digest)
    if replacement != expected_replacement:
        fail("Velero image manager replacement must atomically update the complete image authority block")
    updated_authority = authority_text.replace(velero_match.group(0), replacement, 1)
    expected_authority = authority_text.replace(
        f"VELERO_VERSION={a['VELERO_VERSION']}", "VELERO_VERSION=9.9.9", 1
    ).replace(a["VELERO_IMAGE_DIGEST"], new_velero_digest, 1)
    if updated_authority != expected_authority:
        fail("Velero image manager replacement must preserve adjacent checksum authority")
    ort_zap_pattern_sources = ort_zap_image_manager.get("matchStrings", [None])
    if len(ort_zap_pattern_sources) != 1:
        fail("ORT/ZAP image manager must define one match pattern")
    try:
        ort_zap_pattern = compile_re2_pattern(ort_zap_pattern_sources[0])
    except (re.error, TypeError) as error:
        fail(f"ORT/ZAP image manager pattern is invalid: {error}")
    ort_zap_matches = list(ort_zap_pattern.finditer(authority_text))
    if Counter(match.group("depName") for match in ort_zap_matches) != Counter(
        expected_image_dep_names[x] for x in ("ORT", "ZAP")
    ):
        fail("ORT/ZAP image manager must match each GHCR image exactly once and exclude Velero")
    expected_ort_zap_digests = {
        expected_image_dep_names[key]: a[f"{key}_DIGEST"] for key in ("ORT", "ZAP")
    }
    for match in ort_zap_matches:
        if match.group("currentDigest") != expected_ort_zap_digests[match.group("depName")]:
            fail("ORT/ZAP image manager must pair each GHCR image with its own authority digest")
    if any(match.group("depName") == "velero/velero" for match in ort_zap_matches):
        fail("ORT/ZAP image manager must not match the Velero authority block")
    for manager_index, manager in enumerate(custom_managers):
        patterns = manager.get("matchStrings") if isinstance(manager, dict) else None
        if not isinstance(patterns, list) or not patterns:
            fail(f"Renovate custom manager {manager_index} must define a non-empty matchStrings list")
        for pattern_index, pattern_source in enumerate(patterns):
            if not isinstance(pattern_source, str) or not pattern_source:
                fail(
                    f"Renovate custom manager {manager_index} matchStrings[{pattern_index}] must be a non-empty string"
                )
            try:
                pattern = compile_re2_pattern(pattern_source)
            except re.error as error:
                fail(f"Renovate custom manager {manager_index} matchStrings[{pattern_index}] is invalid: {error}")
            for match in pattern.finditer(authority_text):
                groups = match.groupdict()
                dep_name = groups.get("depName") or manager.get("depNameTemplate")
                current_value = groups.get("currentValue")
                current_digest = groups.get("currentDigest")
                if not dep_name or not (current_value or current_digest):
                    fail(
                        f"Renovate custom manager {manager_index} matchStrings[{pattern_index}] lacks required dependency fields"
                    )
                if current_value:
                    matched.update(((dep_name, current_value),))
    if matched != expected_renovate_dependencies:
        fail("Renovate does not discover every workflow tool authority exactly once")
    rules = renovate.get("packageRules", [])
    runtime_major_rule = next(
        (rule for rule in rules if rule.get("description") == "Keep canonical Node and Python runtime majors"), None
    )
    if runtime_major_rule != {
        "description": "Keep canonical Node and Python runtime majors",
        "matchManagers": ["nodenv", "pyenv"],
        "matchUpdateTypes": ["major"],
        "enabled": False,
    }:
        fail("Renovate must disable only major Node and Python runtime authority updates")
    infra_rule = next((rule for rule in rules if rule.get("groupName") == "infrastructure non-major updates"), None)
    velero_rule = next(
        (
            rule
            for rule in rules
            if rule.get("description") == "Production Velero image changes require promotion evidence"
        ),
        None,
    )
    if infra_rule is None or velero_rule is None or rules.index(velero_rule) <= rules.index(infra_rule):
        fail("production Velero Renovate exception must follow infrastructure automerge")
    if (
        velero_rule.get("matchManagers") != ["kubernetes"]
        or velero_rule.get("matchFileNames") != ["k8s/velero/verify-backups-cronjob.yaml"]
        or velero_rule.get("matchPackageNames") != ["velero/velero"]
        or velero_rule.get("pinDigests") is not False
        or velero_rule.get("automerge") is not False
        or velero_rule.get("enabled") is not False
    ):
        fail("production Velero Renovate exception must disable automated digest projection and merge")

    proto = (root / "gradle/proto-convention.gradle").read_text()
    if (
        "protobuf-gradle-plugin 0.10.0" in proto
        or "libs.plugins.protobuf" not in proto
        or "${gradle.gradleVersion}" not in proto
    ):
        fail("protobuf diagnostic must derive both canonical versions")
    for action in ("setup-gh", "setup-helm"):
        data = (actions / action / "action.yml").read_text()
        if "sha256sum --check --status" not in data:
            fail(f"{action} must verify its archive")
    if (
        "RUNNER_OS" not in (actions / "setup-gh/action.yml").read_text()
        or "RUNNER_ARCH" not in (actions / "setup-gh/action.yml").read_text()
    ):
        fail("setup-gh must reject unsupported platforms")
    lychee = (root / "dev-tools/docs/link-check.sh").read_text()
    for required_lychee_fragment in (
        'source "$ROOT_DIR/config/workflow-tool-versions.env"',
        "/lychee/${LYCHEE_VERSION}",
        "LYCHEE_LINUX_X86_64_MUSL_SHA256",
        "sha256sum --check --status",
        "VERIFIED_MARKER",
        "ARCHIVE=",
        "marker_binary_sha",
        "extracted_sha",
        '"$BIN" --no-progress --cache --cache-exclude-status \'400..=599\' "${OPTIONS[@]}"',
        'mv -f "$staging/lychee" "$BIN"',
        'mv -f "$staged_archive" "$ARCHIVE"',
    ):
        if required_lychee_fragment not in lychee:
            fail(f"local Lychee installer does not consume its authority: {required_lychee_fragment}")
    lychee_curl_pattern = (
        r"(?m)^\s*curl -fsSL --retry 3 --retry-delay 2 --retry-max-time 30 \\\n"
        r"\s*--connect-timeout 10 --max-time 60 \\\n"
        r'\s*"\$URL" -o "\$staged_archive"$'
    )
    if len(re.findall(r"(?m)^\s*curl\b", lychee)) != 1 or len(re.findall(lychee_curl_pattern, lychee)) != 1:
        fail("local Lychee installer must define exactly one curl with canonical bounded retries and timeouts")
    docs = (workflows / "docs.yml").read_text()
    gitignore = (root / ".gitignore").read_text()
    if (
        "lycheeverse/lychee-action@" in docs
        or "run: bash ./dev-tools/docs/link-check.sh" not in docs
        or "path: .lycheecache" not in docs
        or "path: .lychee_cache" in docs
        or "LYCHEE_CACHE" in docs
        or "/.lycheecache\n" not in gitignore
    ):
        fail("docs workflow must use the checksum-verifying Lychee installer")
    for identity in ("outputs.lychee-version", "outputs.lychee-linux-x86-64-musl-sha256"):
        if identity not in docs:
            fail(f"docs Lychee cache omits tool identity: {identity}")
    license_scan = load(workflows / "license-scan.yml")
    license_changes = license_scan.get("jobs", {}).get("changes", {})
    license_outputs = license_changes.get("outputs", {})
    if license_outputs.get("run_gradle_ort") != (
        "${{ steps.filter.outputs.gradle == 'true' || steps.ort_authority.outputs.changed == 'true' }}"
    ) or license_outputs.get("run_npm_ort") != (
        "${{ steps.filter.outputs.npm == 'true' || steps.ort_authority.outputs.changed == 'true' }}"
    ):
        fail("license-scan ORT outputs must include only actual ORT authority changes")
    license_steps = license_changes.get("steps", [])
    ort_authority_steps = [
        step for step in license_steps if isinstance(step, dict) and step.get("id") == "ort_authority"
    ]
    if len(ort_authority_steps) != 1:
        fail("license-scan must define exactly one ORT authority detector")
    ort_authority_step = ort_authority_steps[0]
    if ort_authority_step.get("env", {}).get("BASE_SHA") != (
        "${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}"
    ):
        fail("license-scan ORT authority detector must receive BASE_SHA from GitHub event expressions")
    ort_authority_script = ort_authority_step.get("run", "")
    for required in (
        "config/workflow-tool-versions.env",
        "ghcr\\.io/oss-review-toolkit/ort",
        "ORT_VERSION=",
        "ORT_DIGEST=",
        "git diff --unified=0",
        '[[ -z "$BASE_SHA" || "$BASE_SHA" == 0000000000000000000000000000000000000000 ]]',
        'git diff --unified=0 "$BASE_SHA" "$GITHUB_SHA"',
    ):
        if required not in ort_authority_script:
            fail(f"license-scan ORT authority detector missing: {required}")
    setup_python = load(actions / "setup-python/action.yml")
    if set(setup_python.get("inputs", {})) != {"requirements"}:
        fail("setup-python must expose one canonical requirements profile input")
    setup_source = (actions / "setup-python/action.yml").read_text()
    if "--require-hashes" not in setup_source:
        fail("setup-python must install selected profiles with pip hash verification")
    if 'venv_directory="$(mktemp -d "${RUNNER_TEMP:?}/firemud-python.XXXXXX")"' not in setup_source:
        fail("setup-python must create a fresh runner-temp virtual environment")
    if 'python3 -m venv "$venv_directory"' not in setup_source:
        fail("setup-python must create its isolated environment with the pinned interpreter")
    if '"$venv_python" -m pip install' not in setup_source:
        fail("setup-python must install dependencies through the isolated interpreter")
    if 'printf \'%s\\n\' "$venv_directory/bin" >> "$GITHUB_PATH"' not in setup_source:
        fail("setup-python must expose the isolated interpreter to later steps")
    if re.search(r"(?m)^\s*python3\s+-m\s+pip\s+install\b", setup_source):
        fail("setup-python must not install dependencies into ambient Python")
    if "rm -rf" in setup_source:
        fail("setup-python must not broadly delete runner files while refreshing its environment")
    for profile, requirements_path in requirements_profiles.items():
        relative_path = requirements_path.relative_to(root)
        if f"{profile}) requirements_file={relative_path}" not in setup_source:
            fail(f"setup-python does not own {profile} requirements")
    print("Workflow version authority contract passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
