spring:
  profiles:
    active: dev
  application:
    name: game-logic-service
  flyway:
    enabled: true
    schemas: ${SERVICE_SCHEMA:public},saga
    locations: classpath:db/migration,classpath:db/migration/saga
    defaultSchema: ${SERVICE_SCHEMA:public}

management:
  endpoints:
    access:
      default: read-only
    web:
      exposure:
        include:
          - health
          - prometheus
          - info
  endpoint:
    health:
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,lookDependencyReadiness

grpc:
  shutdownGrace: 30
  server:
    port: 6565
    enableKeepAlive: true
    keepAliveTime: 30s
    keepAliveTimeout: 5s
    permitKeepAliveWithoutCalls: true
    compression: gzip
    security:
      enabled: true
      certificateChainPath: ${FIREMUD_GRPC_CERT_CHAIN_PATH:certs/client.crt}
      privateKeyPath: ${FIREMUD_GRPC_PRIVATE_KEY_PATH:certs/client.key}
      trustCertCollectionPath: ${FIREMUD_GRPC_CA_CERT_PATH:certs/ca.crt}
      clientAuth: REQUIRE

firemud:
  services:
    world-management-service: world-management-service:6565
    entity-management-service: entity-management-service:6565
    social-groups-service: social-groups-service:6565
  communication:
    max-message-length: 512
    defaults:
      say-enabled: true
      whisper-enabled: true
      tell-enabled: true
      whisper-observer-metadata-enabled: true
  grpc:
    cert-chain: ${FIREMUD_GRPC_CERT_CHAIN_PATH:certs/client.crt}
    private-key: ${FIREMUD_GRPC_PRIVATE_KEY_PATH:certs/client.key}
    ca-cert: ${FIREMUD_GRPC_CA_CERT_PATH:certs/ca.crt}
  auth:
    jwt-expiration-ms: 3600000

server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
