redisCoord:
  releaseName: redis-coord
  resetAofOnInstallUpgrade: true
redisCache:
  releaseName: redis-cache
account-service:
  replicaCount: 1
game-session-service:
  replicaCount: 1
tickInterval: 100
features:
  enableFoo: true
