#!/usr/bin/env bash

DEMO_SMOKE_EMAIL=${DEMO_SMOKE_EMAIL:-demo@example.com}
DEMO_SMOKE_PASSWORD=${DEMO_SMOKE_PASSWORD:-swordfish}
DEMO_SMOKE_USERNAME=${DEMO_SMOKE_USERNAME:-demo}
DEMO_SMOKE_WORLD=${DEMO_SMOKE_WORLD:-demo}

export DEMO_SMOKE_EMAIL
export DEMO_SMOKE_PASSWORD
export DEMO_SMOKE_USERNAME
export DEMO_SMOKE_WORLD
