spring:
  profiles:
    active: dev
  application:
    name: logging-admin-service

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
