package net.firedevops.firemud.gamedesign.model;

public enum PublishGateFailureCode {
  PARTICIPANT_SET_MISMATCH,
  PARTICIPANT_UNAVAILABLE,
  PARTICIPANT_SCOPE_MISMATCH,
  UNSUPPORTED_DIGEST_SCHEMA,
  MISSING_CONTENT_DIGEST,
  MISSING_APPLIED_COMMIT,
  MISSING_ABILITY_SCHEMA_DIGEST,
  ABILITY_SCHEMA_DIGEST_OWNER_MISMATCH,
  APPLIED_COMMIT_MISMATCH,
  RECORDED_SCOPE_MISMATCH,
  RECORDED_DIGEST_SCHEMA_MISMATCH,
  RECORDED_CONTENT_DIGEST_MISMATCH
}
