
import net.firedevops.firemud.GenerateTcpProxyDevCertsTask
import org.springframework.boot.gradle.tasks.run.BootRun
import org.gradle.api.tasks.testing.Test
import org.gradle.language.jvm.tasks.ProcessResources

apply(from = "${rootDir}/gradle/proto-convention.gradle")

dependencies {
    annotationProcessor(libs.mapstruct.processor)
    annotationProcessor(libs.lombok)
    annotationProcessor(libs.lombok.mapstruct.binding)
    compileOnly(libs.lombok)
    implementation(libs.flyway.core)
    implementation(libs.mapstruct)
    implementation(libs.spring.boot.starter)
    implementation(libs.spring.boot.starter.actuator)
    implementation("io.netty:netty-all:4.2.7.Final")
    implementation(libs.spring.boot.starter.websocket)
    implementation(project(":common-library"))
    implementation(libs.grpc.spring.boot.starter)
    implementation(libs.micrometer.core)
    implementation(libs.micrometer.registry.prometheus)
    implementation(libs.opentelemetry.api)
    implementation(libs.opentelemetry.sdk)
    implementation(libs.opentelemetry.exporter.otlp)
    testImplementation(libs.testcontainers.junit.jupiter)
    testImplementation(libs.micrometer.registry.prometheus)
    testImplementation("com.squareup.okhttp3:mockwebserver:5.3.2")
    testImplementation(libs.spring.boot.starter.webflux)
    testImplementation(libs.spring.cloud.gateway)
    testImplementation(project(":spring-cloud-gateway"))
}

tasks.named<BootRun>("bootRun") {
    val activeProfile =
        System.getProperty("spring.profiles.active") ?: System.getenv("SPRING_PROFILES_ACTIVE")

    if (activeProfile.isNullOrBlank()) {
        systemProperty("spring.profiles.active", "dev")
    }
}

tasks.register<BootRun>("bootRunLogOnly") {
    group = "application"
    description = "Start the TCP proxy in dev with log-only Telnet handling"
    mainClass.set("net.firedevops.firemud.tcpproxy.TcpProxyServiceApplication")
    classpath = sourceSets.main.get().runtimeClasspath
    systemProperty("spring.profiles.active", "dev")
    environment("TCP_PROXY_LOG_ONLY", "true")
    environment("GATEWAY_WS_URL", "ws://localhost:8080/dev/echo")
}

val generatedDevCertsRelativePath = "build/generated/dev-certs"
val generatedDevCertsResourcePath = "$generatedDevCertsRelativePath/certs"
val effectiveProfile =
    System.getProperty("spring.profiles.active")
        ?: System.getenv("SPRING_PROFILES_ACTIVE")
        ?: "dev"
val autoGenerateDevCerts = effectiveProfile != "prod"
val skipDevCerts = project.hasProperty("skipDevCerts")

sourceSets.main.get().resources.srcDir(generatedDevCertsRelativePath)

val generateTcpProxyDevCerts =
    tasks.register<GenerateTcpProxyDevCertsTask>("generateTcpProxyDevCerts") {
        outputDir.set(layout.buildDirectory.dir(generatedDevCertsResourcePath))
        shouldGenerate.set(autoGenerateDevCerts && !skipDevCerts)
        scriptWorkingDirPath.set(rootProject.projectDir.absolutePath)
    }

tasks.named<ProcessResources>("processResources") {
    dependsOn(generateTcpProxyDevCerts)
    from(generateTcpProxyDevCerts.map { it.outputDir.get().asFile }) {
        into("certs")
    }
    duplicatesStrategy = org.gradle.api.file.DuplicatesStrategy.INCLUDE
}

tasks.withType<BootRun>().configureEach {
    dependsOn(generateTcpProxyDevCerts)
}

tasks.withType<Test>().configureEach {
    dependsOn(generateTcpProxyDevCerts)
}
