
plugins {
    `java-test-fixtures`
    id("net.firedevops.firemud.service-conventions")
}

import java.util.zip.ZipFile
import net.firedevops.firemud.GenerateTcpProxyDevCertsTask
import org.gradle.api.DefaultTask
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.Classpath
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.TaskAction
import org.gradle.work.DisableCachingByDefault
import org.springframework.boot.gradle.tasks.run.BootRun
import org.springframework.boot.gradle.tasks.bundling.BootJar
import org.gradle.language.jvm.tasks.ProcessResources

apply(from = "${rootDir}/gradle/proto-convention.gradle")

dependencies {
    implementation("io.netty:netty-all:4.2.17.Final")
    implementation(libs.spring.boot.starter.websocket)
    implementation(project(":common-security"))
    testImplementation(libs.micrometer.registry.prometheus)
    testImplementation("com.squareup.okhttp3:mockwebserver:5.5.0")
    testImplementation(libs.spring.boot.starter.webflux)
    testImplementation(libs.spring.cloud.gateway)
    testImplementation(libs.spring.boot.starter.test)
    testImplementation(libs.spring.boot.starter.data.redis)
    testImplementation(libs.spring.boot.starter.jdbc)
    testImplementation(testFixtures(project(":common-test-support")))
    testImplementation(project(":entity-management-service"))
    testImplementation(project(":game-session-service"))
    testImplementation(testFixtures(project(":game-session-service")))
    testImplementation(project(":game-logic-service"))
    testImplementation(project(":social-groups-service"))
    testImplementation(project(":spring-cloud-gateway"))
    testImplementation(project(":world-management-service"))
    testCompileOnly(libs.spotbugs.annotations)
    testRuntimeOnly(libs.postgresql)

    testFixturesImplementation(testFixtures(project(":common-test-support")))
}

configurations.named("runtimeClasspath") {
    // TCP Proxy is a stateless edge and must not activate Redis auto-configuration at runtime.
    exclude(group = "org.springframework.boot", module = "spring-boot-starter-data-redis")
}

@DisableCachingByDefault(because = "Verification task produces no outputs")
abstract class VerifyNoRedisRuntime : DefaultTask() {
    @get:Classpath abstract val runtimeClasspath: ConfigurableFileCollection

    @get:InputFile abstract val bootJar: RegularFileProperty

    @TaskAction
    fun verify() {
        val forbiddenModules =
            setOf(
                "spring-boot-starter-data-redis",
                "spring-boot-data-redis",
                "spring-data-redis",
                "lettuce-core",
            )
        val forbiddenRuntimeFiles =
            runtimeClasspath.files
                .map { it.name }
                .filter { entry -> forbiddenModules.any { entry.startsWith("$it-") } }
        check(forbiddenRuntimeFiles.isEmpty()) {
            "TCP Proxy runtimeClasspath contains Redis client modules: ${forbiddenRuntimeFiles.sorted()}"
        }

        val forbiddenEntries =
            ZipFile(bootJar.get().asFile).use { archive ->
                archive.entries().asSequence()
                    .map { it.name.substringAfterLast('/') }
                    .filter { entry ->
                        entry == "TelnetRedisConfiguration.class" ||
                            forbiddenModules.any { entry.startsWith("$it-") }
                    }.toList()
            }
        check(forbiddenEntries.isEmpty()) {
            "TCP Proxy bootJar contains Redis runtime entries: ${forbiddenEntries.sorted()}"
        }
    }
}

val verifyNoRedisRuntime =
    tasks.register<VerifyNoRedisRuntime>("verifyNoRedisRuntime") {
        group = "verification"
        description = "Verifies that the stateless TCP Proxy runtime contains no Redis client."
        runtimeClasspath.from(configurations.named("runtimeClasspath"))
        bootJar.set(tasks.named<BootJar>("bootJar").flatMap { it.archiveFile })
    }

tasks.named("check") {
    dependsOn(verifyNoRedisRuntime)
}

tasks.named<BootRun>("bootRun") {
    val activeProfile =
        System.getProperty("spring.profiles.active") ?: System.getenv("SPRING_PROFILES_ACTIVE")

    if (!activeProfile.isNullOrBlank()) {
        systemProperty("spring.profiles.active", activeProfile)
    }
}

val generatedDevCertsRelativePath = "generated/dev-certs"
val generatedDevCertsResourcePath = "$generatedDevCertsRelativePath/certs"
val effectiveProfile =
    System.getProperty("spring.profiles.active")
        ?: System.getenv("SPRING_PROFILES_ACTIVE")
        ?: ""
val autoGenerateDevCerts = effectiveProfile != "prod"
val skipDevCerts = project.hasProperty("skipDevCerts")

sourceSets.main.get().resources.srcDir(layout.buildDirectory.dir(generatedDevCertsRelativePath))

val generateTcpProxyDevCerts =
    tasks.register<GenerateTcpProxyDevCertsTask>("generateTcpProxyDevCerts") {
        outputDir.set(layout.buildDirectory.dir(generatedDevCertsResourcePath))
        shouldGenerate.set(autoGenerateDevCerts && !skipDevCerts)
        scriptWorkingDirPath.set(rootProject.projectDir.absolutePath)
    }

tasks.named<ProcessResources>("processResources") {
    dependsOn(generateTcpProxyDevCerts)
    from(generateTcpProxyDevCerts.map { it.outputDir.get().asFile }) {
        into("certs")
    }
    duplicatesStrategy = org.gradle.api.file.DuplicatesStrategy.INCLUDE
}

tasks.withType<BootRun>().configureEach {
    dependsOn(generateTcpProxyDevCerts)
}

tasks.withType<org.gradle.api.tasks.testing.Test>().configureEach {
    dependsOn(generateTcpProxyDevCerts)
}
