
plugins {
    `java-test-fixtures`
    id("net.firedevops.firemud.service-conventions")
    id("net.firedevops.firemud.redis-conventions")
}

import net.firedevops.firemud.GenerateTcpProxyDevCertsTask
import org.springframework.boot.gradle.tasks.run.BootRun
import org.gradle.language.jvm.tasks.ProcessResources

apply(from = "${rootDir}/gradle/proto-convention.gradle")

dependencies {
    implementation("io.netty:netty-all:4.2.14.Final")
    implementation(libs.spring.boot.starter.websocket)
    implementation(project(":common-security"))
    testImplementation(libs.micrometer.registry.prometheus)
    testImplementation("com.squareup.okhttp3:mockwebserver:5.3.2")
    testImplementation(libs.spring.boot.starter.webflux)
    testImplementation(libs.spring.cloud.gateway)
    testImplementation(libs.spring.boot.starter.test)
    testImplementation(libs.spring.boot.starter.data.redis)
    testImplementation(libs.spring.boot.starter.jdbc)
    testImplementation(testFixtures(project(":common-test-support")))
    testImplementation(project(":entity-management-service"))
    testImplementation(project(":game-session-service"))
    testImplementation(testFixtures(project(":game-session-service")))
    testImplementation(project(":game-logic-service"))
    testImplementation(project(":social-groups-service"))
    testImplementation(project(":spring-cloud-gateway"))
    testImplementation(project(":world-management-service"))
    testCompileOnly("com.github.spotbugs:spotbugs-annotations:4.9.8")
    testRuntimeOnly(libs.postgresql)
}

tasks.named<BootRun>("bootRun") {
    val activeProfile =
        System.getProperty("spring.profiles.active") ?: System.getenv("SPRING_PROFILES_ACTIVE")

    if (!activeProfile.isNullOrBlank()) {
        systemProperty("spring.profiles.active", activeProfile)
    }
}

val generatedDevCertsRelativePath = "generated/dev-certs"
val generatedDevCertsResourcePath = "$generatedDevCertsRelativePath/certs"
val effectiveProfile =
    System.getProperty("spring.profiles.active")
        ?: System.getenv("SPRING_PROFILES_ACTIVE")
        ?: ""
val autoGenerateDevCerts = effectiveProfile != "prod"
val skipDevCerts = project.hasProperty("skipDevCerts")

sourceSets.main.get().resources.srcDir(layout.buildDirectory.dir(generatedDevCertsRelativePath))

val generateTcpProxyDevCerts =
    tasks.register<GenerateTcpProxyDevCertsTask>("generateTcpProxyDevCerts") {
        outputDir.set(layout.buildDirectory.dir(generatedDevCertsResourcePath))
        shouldGenerate.set(autoGenerateDevCerts && !skipDevCerts)
        scriptWorkingDirPath.set(rootProject.projectDir.absolutePath)
    }

tasks.named<ProcessResources>("processResources") {
    dependsOn(generateTcpProxyDevCerts)
    from(generateTcpProxyDevCerts.map { it.outputDir.get().asFile }) {
        into("certs")
    }
    duplicatesStrategy = org.gradle.api.file.DuplicatesStrategy.INCLUDE
}

tasks.withType<BootRun>().configureEach {
    dependsOn(generateTcpProxyDevCerts)
}

tasks.withType<org.gradle.api.tasks.testing.Test>().configureEach {
    dependsOn(generateTcpProxyDevCerts)
}
