CREATE TABLE IF NOT EXISTS ${serviceSchema}.saga_instance (
  id BIGSERIAL PRIMARY KEY,
  saga_name VARCHAR(100) NOT NULL,
  state VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
