---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: firemud
  name: firemud-config
data:
  FIREMUD_POSTGRES_HOST: postgres
  FIREMUD_POSTGRES_PORT: "5432"
  FIREMUD_POSTGRES_DB: firemud
  FIREMUD_REDIS_COORD_HOST: redis-coord
  FIREMUD_REDIS_COORD_PORT: "6379"
  FIREMUD_REDIS_CACHE_HOST: redis-cache
  FIREMUD_REDIS_CACHE_PORT: "6379"
  FIREMUD_AUTH_JWT_SECRET_PATH: /var/run/secrets/firemud/jwt/current.key
  FIREMUD_AUTH_JWKS_PATH: /var/run/secrets/firemud/jwks/jwks.json
  OTEL_ENDPOINT: http://otel-collector:4317
  FLUENT_ELASTICSEARCH_HOST: elasticsearch
  FLUENT_ELASTICSEARCH_PORT: "9200"
---
apiVersion: v1
kind: Secret
metadata:
  namespace: firemud
  name: postgres-credentials
data:
  FIREMUD_POSTGRES_USER: ZmlyZW11ZA==
  FIREMUD_POSTGRES_PASSWORD: ZmlyZW11ZA==
---
apiVersion: v1
kind: Secret
metadata:
  namespace: firemud
  name: jwt-signing-keys
type: Opaque
stringData:
  current.key: changeit-changeit-changeit-changeit
---
apiVersion: v1
kind: Secret
metadata:
  namespace: firemud
  name: jwt-jwks
type: Opaque
stringData:
  jwks.json: '{"keys":[]}'
