---
apiVersion: v1
kind: ConfigMap
metadata:
  name: firemud-config
data:
  FIREMUD_POSTGRES_HOST: postgres
  FIREMUD_POSTGRES_PORT: "5432"
  FIREMUD_POSTGRES_DB: firemud
  FIREMUD_REDIS_HOST: redis
  FIREMUD_REDIS_PORT: "6379"
  OTEL_ENDPOINT: http://otel-collector:4317
  FLUENT_ELASTICSEARCH_HOST: elasticsearch
  FLUENT_ELASTICSEARCH_PORT: "9200"
---
apiVersion: v1
kind: Secret
metadata:
  name: firemud-secret
data:
  FIREMUD_POSTGRES_USER: ZmlyZW11ZA==
  FIREMUD_POSTGRES_PASSWORD: ZmlyZW11ZA==
  FIREMUD_AUTH_JWT_SECRET: Y2hhbmdlaXQtY2hhbmdlaXQtY2hhbmdlaXQtY2hhbmdlaXQ=

