---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: firemud
  name: spring-cloud-gateway-ingress
spec:
  podSelector:
    matchLabels:
      app: spring-cloud-gateway
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: tcp-proxy-service
      ports:
        - protocol: TCP
          port: 8443
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
      ports:
        - protocol: TCP
          port: 8080
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 6565
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: firemud
  name: tcp-proxy-service-egress
spec:
  podSelector:
    matchLabels:
      app: tcp-proxy-service
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - podSelector:
            matchLabels:
              app: elasticsearch
      ports:
        - protocol: TCP
          port: 9200
    - to:
        - podSelector:
            matchLabels:
              app: spring-cloud-gateway
      ports:
        - protocol: TCP
          port: 8443
    - to:
        - podSelector:
            matchLabels:
              app: game-session-service
      ports:
        - protocol: TCP
          port: 6565
    - to:
        - podSelector:
            matchLabels:
              app: otel-collector
      ports:
        - protocol: TCP
          port: 4317
