apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: firemud
  name: internal-services-egress
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: NotIn
        values:
          - spring-cloud-gateway
          - tcp-proxy-service
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: firemud-postgresql
      ports:
        - protocol: TCP
          port: 5432
    - to:
        - podSelector:
            matchLabels:
              app: redis-coord
        - podSelector:
            matchLabels:
              app: redis-cache
      ports:
        - protocol: TCP
          port: 6379
    - to:
        - podSelector:
            matchExpressions:
              - key: app
                operator: NotIn
                values:
                  - spring-cloud-gateway
                  - tcp-proxy-service
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 6565
        - protocol: TCP
          port: 4317
