spring:
  profiles:
    active: dev
  application:
    name: spring-cloud-gateway

---

spring:
  config:
    activate:
      on-profile: dev
  cloud:
    gateway:
      routes:
        - id: session
          uri: http://game-session-service:8080
          predicates:
            - Path=/api/session/**
        - id: admin
          uri: http://logging-admin-service:8080
          predicates:
            - Path=/api/admin/**
        - id: design
          uri: http://game-design-service:8080
          predicates:
            - Path=/api/design/**

---

spring:
  config:
    activate:
      on-profile: prod
  cloud:
    gateway:
      routes:
        - id: session
          uri: http://game-session-service.default.svc.cluster.local:8080
          predicates:
            - Path=/api/session/**
        - id: admin
          uri: http://logging-admin-service.default.svc.cluster.local:8080
          predicates:
            - Path=/api/admin/**
        - id: design
          uri: http://game-design-service.default.svc.cluster.local:8080
          predicates:
            - Path=/api/design/**

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
