spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: session
              uri: http://game-session-service:8080
              predicates:
                - Path=/api/session/**
