spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: session
              uri: ws://game-session-service:8080
              predicates:
                - Path=/api/session/**,/ws/game/**
