spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: session
              uri: http://game-session-service:8080
              predicates:
                - Path=/api/session/**
              filters:
                - StripPrefix=2
            - id: admin
              uri: http://logging-admin-service:8080
              predicates:
                - Path=/api/admin/**
              filters:
                - StripPrefix=2
            - id: design
              uri: http://game-design-service:8080
              predicates:
                - Path=/api/design/**
              filters:
                - StripPrefix=2
            - id: account
              uri: http://account-service:8080
              predicates:
                - Path=/api/account/**
              filters:
                - StripPrefix=2
            - id: social
              uri: http://social-groups-service:8080
              predicates:
                - Path=/api/social/**
              filters:
                - StripPrefix=2
            - id: asset-store
              uri: http://minio:9000
              predicates:
                - Path=/assets/**
              filters:
                - StripPrefix=1 # remove /assets before forwarding
