syntax = "proto3";

package world_management.v1;

option java_package = "net.firedevops.firemud.worldmanagement.v1";
option java_multiple_files = true;

service WorldManagementService {
  rpc GetRoom(GetRoomRequest) returns (GetRoomResponse);
  rpc UpdateWorldState(UpdateWorldStateRequest) returns (UpdateWorldStateResponse);
}

message GetRoomRequest {
  string tenant_id = 1;
  string room_id = 2;
}

message GetRoomResponse {
  string room_json = 1;
}

message UpdateWorldStateRequest {
  string tenant_id = 1;
}

message UpdateWorldStateResponse {
  bool success = 1;
}
