name: Manual Helm Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up kubectl
        uses: azure/setup-kubectl@v5
      - name: Set up Helm
        uses: azure/setup-helm@v5
      - name: Deploy with Helm
        run: |
          helm upgrade --install firemud ./k8s/helm/firemud \
            -f k8s/helm/values-local.yaml
