name: Release Please

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  release:
    name: Create Release PR
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5
        with:
          egress-policy: audit

      - name: 🚀 Run Release Please
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: config/release/.release-please-config.json
          manifest-file: config/release/.release-please-manifest.json
